<div itemprop="description">
						<section class="section_offset">
								<header class="top_box on_the_sides">
									<div class="left_side clearfix v_centered">
										<div class="v_centered">
											<h3><?=$translates['front.search.count.found'].': '.count($data_without_cost)?></h3>
										</div>
									</div>
									<div class="right_side">
										<!--<div class="layout_type buttons_row" data-table-container="#products_container">
											<a href="#" data-table-layout="grid_view" class="button_grey middle_btn icon_btn tooltip_container"><i class="icon-th"></i><span class="tooltip top">Grid View</span></a>
											<a href="#" data-table-layout="list_view list_view_products" class="button_grey middle_btn icon_btn active tooltip_container"><i class="icon-th-list"></i><span class="tooltip top">List View</span></a>
										</div>-->
									</div>
								</header>
								<div class="table_layout list_view list_view_products" id="products_container test">
									<div class="table_row"> 
									<?php 
									$i=1;
									if (count($data_without_cost) > 0) {
									foreach ($data_without_cost as $fetchData)
									{ 
										include("product.phtml");	
										$i++;
									}
									} else {
										?>
										<div class="table_cell">
											<div class="product_item">
												<div class="full_description">
													<h1 class="align_center"><?=$translates["f.netu_produktov"];?>!</h1>
												</div>
												<div class="description">
													<h1 class="align_center"><?=$translates["f.netu_produktov"];?>!</h1>
												</div>
												
											</div>
										</div>
										<?php
									}
									?>
									</div>
								</div>
								
						</section>
						
						<!-- Start pagination -->
						<script>
							$(document).ready(function(){
								var pages = $('input[name=pages]').val();
								for (var i=11; i<=pages; i++)
								{
									$('#page-item-'+i).css('display', 'none');
								}
							});
							
							function changePage(page)
							{
								pages = $('input[name=pages]').val();
								for (var i=1; i<=pages; i++) {
									$('#page-item-'+i).css('display', 'none');
								}
								
								for (var c=1; c<50; c++)
								{
									if (page==c)
									{
										var endFor=c+'0';
										var startFor=parseInt(endFor)-9;
										for (var i=startFor; i<=parseInt(endFor); i++)
										{
											$('#page-item-'+i).css('display', 'block');
										}
									}
								}
								/*
								if (page==1) {
									for (var i=1; i<=10; i++) {
										$('#page-item-'+i).css('display', 'block');
									}
								}*/
							}
						</script>
						
						<div>
							<center>	
								<nav>
								  <ul class="pagination pagination-lg">
									<li>
									  <a href="#" aria-label="Previous">
										<span aria-hidden="true">&laquo;</span>
									  </a>
									</li>
									<?php
										$total_article = $i-1;
										$total_page = ceil($total_article/10);	
										echo "<input type='hidden' name='pages' value='".$total_article."'>";	
										
										for ($c=1; $c<=$total_page; $c++)
										{	
											echo "<li> <a href='#' onclick='changePage(".$c.")'> $c </a> </li>";
										}
									?>
									<li>
									  <a href="#" aria-label="Next">
										<span aria-hidden="true">&raquo;</span>
									  </a>
									</li>
								  </ul>
								</nav>
							</center>
						</div>
						<!-- End pagination -->

				