<h1 class="h1-header">
<span><?=$title;?></span>
<a href="<?=$listUrl;?>" class="btn btn-blue"><?=$listTitle;?></a>
</h1>
<form action="/staffcp/<?=$this->dataModel->getModelName();?>/save/" method="POST" enctype="multipart/form-data">
<div id="tabs" class="tabs">
    <ul>
    	<?foreach ($tabs as $tabId=>$tabName){?>
        <li><a href="#tab-<?=$tabId;?>"><span><?=$tabName;?></span></a></li>
        <?}?>
    </ul>
    <?foreach ($tabs as $tabId=>$tabName){?>
    <div id="tab-<?=$tabId;?>">
	<table class="form">
	<?foreach ($tabFields[$tabName] as $fieldName=>$field){?>
		<?if ($field->hasLayout){ 
		
		if ($fieldName=='ru') {
		
		?>
		<script>
			function urlRusLat(str) {
				str = str.toLowerCase();
					var cyr2latChars = new Array(
							['а', 'a'], ['б', 'b'], ['в', 'v'], ['г', 'g'],
							['д', 'd'],  ['е', 'e'], ['ё', 'yo'], ['ж', 'zh'], ['з', 'z'],
							['и', 'i'], ['й', 'y'], ['к', 'k'], ['л', 'l'],
							['м', 'm'],  ['н', 'n'], ['о', 'o'], ['п', 'p'],  ['р', 'r'],
							['с', 's'], ['т', 't'], ['у', 'u'], ['ф', 'f'],
							['х', 'h'],  ['ц', 'c'], ['ч', 'ch'],['ш', 'sh'], ['щ', 'shch'],
							['ъ', ''],  ['ы', 'y'], ['ь', ''],  ['э', 'e'], ['ю', 'yu'], ['я', 'ya'],
							
							['А', 'A'], ['Б', 'B'],  ['В', 'V'], ['Г', 'G'],
							['Д', 'D'], ['Е', 'E'], ['Ё', 'YO'],  ['Ж', 'ZH'], ['З', 'Z'],
							['И', 'I'], ['Й', 'Y'],  ['К', 'K'], ['Л', 'L'],
							['М', 'M'], ['Н', 'N'], ['О', 'O'],  ['П', 'P'],  ['Р', 'R'],
							['С', 'S'], ['Т', 'T'],  ['У', 'U'], ['Ф', 'F'],
							['Х', 'H'], ['Ц', 'C'], ['Ч', 'CH'], ['Ш', 'SH'], ['Щ', 'SHCH'],
							['Ъ', ''],  ['Ы', 'Y'],
							['Ь', ''],
							['Э', 'E'],
							['Ю', 'YU'],
							['Я', 'YA'],
							
							['a', 'a'], ['b', 'b'], ['c', 'c'], ['d', 'd'], ['e', 'e'],
							['f', 'f'], ['g', 'g'], ['h', 'h'], ['i', 'i'], ['j', 'j'],
							['k', 'k'], ['l', 'l'], ['m', 'm'], ['n', 'n'], ['o', 'o'],
							['p', 'p'], ['q', 'q'], ['r', 'r'], ['s', 's'], ['t', 't'],
							['u', 'u'], ['v', 'v'], ['w', 'w'], ['x', 'x'], ['y', 'y'],
							['z', 'z'],
							
							['A', 'A'], ['B', 'B'], ['C', 'C'], ['D', 'D'],['E', 'E'],
							['F', 'F'],['G', 'G'],['H', 'H'],['I', 'I'],['J', 'J'],['K', 'K'],
							['L', 'L'], ['M', 'M'], ['N', 'N'], ['O', 'O'],['P', 'P'],
							['Q', 'Q'],['R', 'R'],['S', 'S'],['T', 'T'],['U', 'U'],['V', 'V'],
							['W', 'W'], ['X', 'X'], ['Y', 'Y'], ['Z', 'Z'],
							
							[' ', '_'],['0', '0'],['1', '1'],['2', '2'],['3', '3'],
							['4', '4'],['5', '5'],['6', '6'],['7', '7'],['8', '8'],['9', '9'],
							['-', '-']

				);

				var newStr = new String();

				for (var i = 0; i < str.length; i++) {

					ch = str.charAt(i);
					var newCh = '';

					for (var j = 0; j < cyr2latChars.length; j++) {
						if (ch == cyr2latChars[j][0]) {
							newCh = cyr2latChars[j][1];

						}
					}
					newStr += newCh;

				}
				var newname = "f."+newStr.replace(/[_]{2,}/gim, '_').replace(/\n/gim, '');
				$( "input[name='form[code]']" ).attr('value',newname);
				$( "input[name='form[en]']" ).attr('value',str);
				$( "input[name='form[de]']" ).attr('value',str);
				$( "input[name='form[fr]']" ).attr('value',str);
				$( "input[name='form[it]']" ).attr('value',str);
				$( "input[name='form[gr]']" ).attr('value',str);
				$( "input[name='form[no]']" ).attr('value',str);
				$( "input[name='form[da]']" ).attr('value',str);
				$( "input[name='form[es]']" ).attr('value',str);
				$( "input[name='transalateee']" ).attr('value',"$translates['"+newname+"']");
				$( "input[name='transalateeeasda']" ).attr('value',"<? echo htmlspecialchars_decode('&lt;?=$translates[\""+newname+"\"];?>');?>");
			}
			</script>
		<tr>
			<td class="label"><?=$this->dataModel->getFieldLabel($fieldName);?>ru</td>
			<td><input type="text" name="form[ru]" onchange="urlRusLat(this.value)" style="width:99%;"> <br/>
				<input type="text" name="transalateee" style="width:99%;" value=""> <br/>
				<input type="text" name="transalateeeasda" style="width:99%;" value=""> <br/>
			</td>
		</tr>
		<?
		
		} else { ?>
		<tr>
			<td class="label"><?=$this->dataModel->getFieldLabel($fieldName);?></td>
			<td><?=$field->getFormValue();?></td>
		</tr>
		<?}}?>
	<?}?>
	</table>
	</div>
    <?}?>
</div>
<input type="submit" value="<?=$submit?>" id="submit_action" class="btn btn-blue">
</form>