<?php
$actions = array();
$actions = $this->dataModel_banners->getDisabledFields();
if (empty($actions)) $actions = array();
?>

<h1>
	<span>Баннеры</span>
	<?php if (!in_array("add", $actions)){?>
		<?php if ($acl->canViewMenuItem($addUrl_banners)){?>
		<input type="button" name="" value="<?=$addTitle_banners;?>" onclick="location='<?=$addUrl_banners;?>';" class="btn btn-blue"/>
		<?php }?>
	<?php }?>
</h1>

<br>
<div class="clear"></div>

<table class="list">
	<thead>
	<tr>
		<?foreach ($fieldTitles_banners as $fieldTitle){?>
		<th><?=$fieldTitle;?></th>
		<?}?>
		<?if (!in_array("edit", $actions)){?><th><img title="<?=$translates['admin.main.edit']?>" border="0" src="/staffcp/media/images/pencil_16.png"/></th><?}?>
		<?if (!in_array("delete", $actions)){?><th><img title="<?=$translates['admin.main.delete']?>" border="0" src="/staffcp/media/images/trash_16.png"/></th><?}?>
	</tr>
	</thead>
	<tbody>
	<?foreach ($data_banners as $row){?>
		<? $dataModel_banners->setValues($row);?>
		<tr>
			<?foreach ($dataModel_banners->getListFields() as $field){?>
			<td><?=$field->getViewValue();?></td>
			<?}?>
			<?if ($acl->canViewMenuItem($dataModel_banners->getModelName().'/edit/?'.$indexField_banners.'='.$row[$indexField_banners])){?>
			
			<?if (!in_array("edit", $actions)){?>
			<td width="25px;" style="text-align:right;"><a href="/staffcp/<?=$dataModel_banners->getModelName();?>/edit/?<?=$indexField_banners;?>=<?=$row[$indexField_banners];?>"><img title="<?=$translates['admin.main.edit']?>" border="0" src="/staffcp/media/images/pencil_16.png"/></a></td>
			<?}?>
			
			<?if (!in_array("delete", $actions)){?>
			<td width="25px;" style="text-align:right;"><a href="/staffcp/<?=$dataModel_banners->getModelName();?>/delete/?<?=$indexField_banners;?>=<?=$row[$indexField_banners];?>" onclick="return confirm('<?=$translates['admin.main.confirm']?>');"><img title="<?=$translates['admin.main.delete']?>" border="0" src="/staffcp/media/images/trash_16.png"/></a></td>
			<?}?>
			
			<?} else {?>
			<td width="100" align="center"><i><?=$translates['admin.main.deny']?></i></td>
			<td width="50" align="center"><i><?=$translates['admin.main.deny']?></i></td>
			<?}?>
		</tr>
	<?}?>
	</tbody>
</table>