<div class="container">
	<ul class="breadcrumbs">
        <li>
            <?=$bread?>
        </li>
    </ul>
    <div class="row">
        <aside class="col-md-3 col-sm-4">
            <?php $this->block('account/left_menu');?>	
        </aside>
        <main class="col-md-9 col-sm-8">
			<h1><?=$translates['front.changepassword']?></h1>
            <section class="theme_box">
				<header class="on_the_sides">
					<div class="left_side">
						<?php if (isset($errors) && count($errors)>0){?>
							<br/>
							<ul class="simple_vertical_list">
								<?php foreach ($errors as $dd){?>
									<li class="error"><?=$dd?></li>
								<?php }?>
							</ul>
							<br/>
						<?php }?>
					</div>
					<div class="right_side"></div>
				</header>
				<form action="<?=HTTP_ROOT?>/account/change/" method="POST">
					<ul>
						<li class="row">
							<div class="col-xs-12">
									<label for="input_1"><?=$translates['front.pass.old']?></label>
									<div class="form_el">
										<input type="password" id="input_1" name="form[old_pass]" placeholder="<?=$translates['front.pass.old']?>" required>
									</div>
							</div>
						</li>
						
						<li class="row">
							<div class="col-xs-12">
									<label for="input_2"><?=$translates['front.pass.new']?></label>
									<div class="form_el">
										<input type="password" id="input_2" name="form[pass1]" placeholder="<?=$translates['front.pass.new']?>" required>
									</div>
							</div>
						</li>
						
						<li class="row">
							<div class="col-xs-12">
									<label for="input_3"><?=$translates['front.pass.repeat']?></label>
									<div class="form_el">
										<input type="password" id="input_3" name="form[pass2]" placeholder="<?=$translates['front.pass.repeat']?>" required>
									</div>
							</div>
						</li>
						<li class="row">
							<div class="col-xs-12">
								<div class="form_el">
									<input class="button_blue" type="submit" value="<?=$translates['front.send']?>">
								</div>
							</div>
						</li>
					</ul>
				</form>
			</section>
        </main>
    </div>
</div>