<div id="login_mw" class="modal_window">

	<button class="close arcticmodal-close"></button>

	<header class="on_the_sides">
		<div class="left_side">

			<h2><?=$translates['front.profile.name']?></h2>

		</div>

		<div class="right_side">

			<a href="<?=HTTP_ROOT?>/account/signup/" class="button_grey middle_btn"><?=$translates['front.act.reg']?></a>

		</div>

	</header>

	<form class="type_2" action="<?=HTTP_ROOT?>/account/login/" method="POST">

		<ul>

			<li>
				<label for="login_email"><?=$translates['front.account.email']?></label>
				<input type="email" name="form[email]" id="login_email" required>
			</li>

			<li>
				<label for="login_password"><?=$translates['front.account.password']?></label>
				<input type="password" name="form[pass]" id="login_password" required>
			</li>

			<li>
				<input type="checkbox" name="form[rememberme]" id="checkbox_1" value="1">
				<label for="checkbox_1"><?=$translates['rememderme']?></label>
			</li>

			<li class="v_centered">
				<button class="button_blue middle_btn"><?=$translates['front.profile.enter']?></button>
				<a href="<?=HTTP_ROOT?>/account/remide/" class="small_link"><?=$translates['front.profile.forgot']?></a>
			</li>

		</ul>

	</form>

</div>