<style>
.popup-connect-price { box-shadow:0 0 35px #999999; width:550px; z-index:1; position:absolute; padding:10px; margin:0 auto; background:#fff; border:solid 1px #dadada; }
.popup-connect-price input { text-align:center; }
</style>

<?php
$actions = array();
$actions = $this->dataModel->getDisabledFields();
if (empty($actions)) $actions = array();
?>


<h1 class="h1-header">
	<span><?=$title;?> (<?=(isset($total)?$total:0)?> записей)</span>
	<?php /*if (!in_array("add", $actions)){?>
		<?php if ($acl->canViewMenuItem($addUrl)){?>
		<input type="button" name="" value="<?=$addTitle;?>" onclick="location='<?=$addUrl;?>';" class="btn btn-blue">
		<?php }?>
	<?php }*/?>
</h1>


<?php if (isset($tableajax) && $tableajax) {?>
	<?php if ($totalPage>1) {?>
	<div class="simple-paging">
	Страницы: <?=PagingViewHelper::paging("/staffcp/".$this->_controller."/?page=:page:",$totalPage,$currentPage);?>
	</div>
	<?php }?>
	<div class="static-search-ajax f-right">
	<form action="">
		Поиск по ID: 
		<input type="text" name="search" value="<?=$search?>" class="iput">
		<input type="submit" value="искать" class="btn btn-blue">
	</form>
	</div>
	<div class="static-search-ajax f-right">
	<form action="http://autoresurs.de/staffcp/products/" method="GET">
		Номер страницы: 
		<input type="text" name="page" value="<?=isset($_GET["page"])?$_GET["page"]:''?>" class="iput">
		<input type="submit" value="искать" class="btn btn-blue">
	</form>
	</div>
	<div class="static-search-ajax f-right">
	<form action="">
		Номер по ART NR: 
		<input type="text" name="search_artnr" value="<?=$search_artnr?>" class="iput">
		<input type="submit" value="искать" class="btn btn-blue">
	</form>
	</div>
	<div class="static-search-ajax f-right">
	<a href="/staffcp/products/?bez=1" class="btn btn-blue">Продукты с ценой выше нуля</a>
	</div>
	
<?php }?>

<?/*=isset($descrhtml)?$descrhtml:''*/?>

<form action="/staffcp/<?=$dataModel->getModelName();?>/" method="POST">
<input type="hidden" name="parent" value="<?=$parent?>"/>
<table class="list<?=(isset($tableajax)&&$tableajax)?'-ajax':'';?>">
	<thead>
	<tr>
		<?php if (!in_array("delete", $actions)){?><th width="30px;"><input class="status_check" type="checkbox" onclick="checked_all();"/></th><?}?>
		<?php foreach ($fieldTitles as $fieldTitle){?>
		<th><?=$fieldTitle;?></th>
		<?php }?>
		<th>Артикул</th>
		<?php if (!in_array("edit", $actions)){?><th width="10"><?=$translates['admin.details.price']?></th><?}?>
		<?php/* if (!in_array("edit", $actions)){?><th width="10"><?=$translates['admin.cat.viewsite']?></th><?}*/?>
		<?php if (!in_array("edit", $actions)){?><th><img title="<?=$translates['admin.main.edit']?>" border="0" src="/staffcp/media/images/pencil_16.png"/></th><?}?>
		<?php if (!in_array("delete", $actions)){?><th><img title="<?=$translates['admin.main.delete']?>" border="0" src="/staffcp/media/images/trash_16.png"/></th><?}?>
	</tr>
	</thead>
	<tbody>
	<?php foreach ($data as $row){?>
		<?php $dataModel->setValues($row);?>
		<?php $get = ProductsModel::getById($row[$indexField]);?>
		<?php $CountP = ProductsModel::getAllPricesCount($row[$indexField])?>
		<tr>
			<?php if (!in_array("delete", $actions)){?><td><input class="input_check" style="margin-left:19px;" type="checkbox" name="delete_list[]" value="<?=$row[$indexField];?>"/></td><?}?>
			<?php foreach ($dataModel->getListFields() as $field){?>
			<td><?=$field->getViewValue();?></td>
			<?php }?>
			
			<td><?=$get['art_nr']?></td>
			
			
			<?php if ($acl->canViewMenuItem($dataModel->getModelName().'/edit/?'.$indexField.'='.$row[$indexField])){?>
			
				<?php if (!in_array("edit", $actions)){?>
				<td align="center">
					<?=$get['price']?>
				</td>
				<?php }?>
								
				<?php /*/if (!in_array("edit", $actions)){?>
				<td align="center">
					<input type="checkbox" name="view<?=$row[$indexField]?>" id="view<?=$row[$indexField]?>" value="1" <?=($get['set_isset']==1)?'checked':''?> onchange="set_isset(<?=$row[$indexField]?>);" />
				</td>
				<?php } */?>
				
				<?php if (!in_array("edit", $actions)){?>
				<td align="center"><a href="/staffcp/<?=$dataModel->getModelName();?>/edit/?parent=<?=$parent?>&<?=$indexField;?>=<?=$row[$indexField];?>"><img title="<?=$translates['admin.main.edit']?>" border="0" src="/staffcp/media/images/pencil_16.png"/></a></td>
				<?php }?>
				
				<?php if (!in_array("delete", $actions)){?>
				<td width="50" align="center">
					<a href="/staffcp/<?=$dataModel->getModelName();?>/delete/?parent=<?=$parent?>&<?=$indexField;?>=<?=$row[$indexField];?>" onclick="return confirm('<?=$translates['admin.main.confirm']?>');"><img title="<?=$translates['admin.main.delete']?>" border="0" src="/staffcp/media/images/trash_16.png"/></a>
				</td>
				<?php }?>
			
			<?php } else {?>
				<td align="center"><i><?=$translates['admin.main.deny']?></i></td>
				<td align="center"><i><?=$translates['admin.main.deny']?></i></td>
				<td align="center"><i><?=$translates['admin.main.deny']?></i></td>
				<td align="center"><i><?=$translates['admin.main.deny']?></i></td>
			<?php }?>
		</tr>
		
	<?php }?>
	</tbody>
	<tfoot>
		<td colspan="5">
		<?php if (!in_array("delete", $actions)){?>
			<button type="submit" name="action" value="delete_list" class="btn btn-red" onsubmit="return confirm('<?=$translates['admin.main.confirm']?>');return false;"><?=$translates['admin.main.delete']?></button>
		<?php }?>
		</td>
		<td></td>
		<td></td>
		<!--<td><button type="submit" name="action" value="save_articles" class="btn btn-green">Сохранить</button></td>-->
		<td></td>
		<td></td>
		<!--<td><button type="submit" name="action" value="save_prices" class="btn btn-green">Сохранить</button></td>-->
	</tfoot>
</table>
</form>

<?php if ((isset($tableajax) && $tableajax) && (isset($totalPage)&&$totalPage>1)) {?>
<div class="clear top-20"></div>
<div class="paging-ajax">
	<?=PagingViewHelper::paging("/staffcp/".$this->_controller."/?page=:page:",$totalPage,$currentPage);?>
</div>
<?php }?>