<div id="tab-importers">
<table cellpadding="5px" class="form" style="width:550px;">
<?php if (isset($listPriceImporters) && count($listPriceImporters)>0){?>
<tr>
	<td style="text-align:center; width:150px;"></td>
	<td style="text-align:center;"><b>Артикул</b></td>
	<td style="text-align:center;"><b>Бренд</b></td>
	<?php if (IS_BELARUS){?>
	<td style="text-align:center;"><b>Удаленный банк цен api.iauto.by</b></td>
	<?php }?>
</tr>
<?php $i=0; foreach ($listPriceImporters as $dd){ $i++;?>
<tr style="background:#<?=($i%2)?'f1f1f1':'ffffff'?>;">
	<td style="text-align:center;"><b><?=$dd['name']?></b></td>
	<td style="text-align:center;"><input type="text" name="p2i_key[<?=$dd['id']?>]" value="<?=$dd['p2i_key']?>"/></td>
	<td style="text-align:center;"><input type="text" name="p2i_key_brand[<?=$dd['id']?>]" value="<?=$dd['p2i_key_brand']?>"/></td>
	<?php if (IS_BELARUS){?>
	<td style="text-align:center;"><input type="checkbox" <?=($dd['p2i_remote_server'])?'checked="checked"':''?> name="p2i_remote_server[<?=$dd['id']?>]" value="<?=$dd['id']?>"/></td>
	<?php }?>
</tr>
<?php }?>
<?php }?>
</table>
</div>