<div  id="result-margins">
<table>
<tr>
	<td colspan="4">
		<?php if (isset($margins_fromto) && count($margins_fromto)>0){?>
		<?php $i=0;?>
		<?php foreach ($margins_fromto as $dd){?>
		<?php $i++;?>
			<div class="<?=($i%2)?'odd':'even';?>" id="pos-mft-<?=$dd['id']?>">
				<?=$dd['from']?> ... <?=$dd['to']?> = <?=$dd['margin']?> % 
				<a href="#" onclick="$('#pos-mft-<?=$dd['id']?>').remove();margins_delete('<?=$dd['id']?>');return false;"><img src="/staffcp/media/images/trash_16.png"/></a>
			</div>
		<?php }?>
		<br/>
		<?php }?>
	</td>
</tr>
<tr>
	<td>от <input type="text" id="margins-from" value="" class="i" style="width:50px;"/></td>
	<td>до <input type="text" id="margins-to" value="" class="i" style="width:50px;"/></td>
	<td>= <input type="text" id="margins-extra" value="" class="i" style="width:50px;"/> %</td>
	<td><a href="#" onclick="margins_fromto();"><img src="/staffcp/media/images/plus.gif"/></a> <img id="ajax1" style="display:none;" src="/staffcp/media/images/2-0.gif"/></td>
</tr>
</table>
<script>
function margins_fromto(){
	$('#ajax1').show();
	var margins_from = $('#margins-from').val();
	var margins_to = $('#margins-to').val();
	var margins_extra = $('#margins-extra').val();
	$.post('/staffcp/margins/margins_fromto/?act=add&margin_id=<?=$margs['id']?>&margins_from='+margins_from+'&margins_to='+margins_to+'&margins_extra='+margins_extra, null,
		function(data) {
			$("#result-margins").html(data);
		}
	);
}
function margins_delete(id){
	$.post('/staffcp/margins/margins_fromto_delete/?id='+id, null);
}
</script>
</div>