<?
$actions = array();
$actions = $this->dataModel_emails->getDisabledFields();
if (empty($actions)) $actions = array();
?>

<h1 class="h1-header">
	<span><?=$title;?></span>
	<?php if (!in_array("add", $actions)){?>
		<?php if ($acl->canViewMenuItem($addUrl_emails)){?>
		<input type="button" name="" value="<?=$addTitle_emails;?>" onclick="location='<?=$addUrl_emails;?>';" class="btn btn-blue">
		<?php }?>
	<?php }?>
</h1>

<table class="list">
	<thead>
	<tr>
		<?foreach ($fieldTitles_emails as $fieldTitle){?>
		<th><?=$fieldTitle;?></th>
		<?}?>
		<?if (!in_array("edit", $actions)){?><th><img title="<?=$translates['admin.main.edit']?>" border="0" src="/staffcp/media/images/pencil_16.png"/></th><?}?>
		<?if (!in_array("delete", $actions)){?><th><img title="<?=$translates['admin.main.delete']?>" border="0" src="/staffcp/media/images/trash_16.png"/></th><?}?>
	</tr>
	</thead>
	<tbody>
	<?foreach ($data_emails as $row){?>
		<? $dataModel_emails->setValues($row);?>
		<tr>
			<?foreach ($dataModel_emails->getListFields() as $field){?>
			<td><?=$field->getViewValue();?></td>
			<?}?>
			<?if ($acl->canViewMenuItem($dataModel_emails->getModelName().'/edit/?'.$indexField_emails.'='.$row[$indexField_emails])){?>
			
			<?if (!in_array("edit", $actions)){?>
			<td width="25px;" style="text-align:right;"><a href="/staffcp/<?=$dataModel_emails->getModelName();?>/edit/?<?=$indexField_emails;?>=<?=$row[$indexField_emails];?>"><img title="<?=$translates['admin.main.edit']?>" border="0" src="/staffcp/media/images/pencil_16.png"/></a></td>
			<?}?>
			
			<?if (!in_array("delete", $actions)){?>
			<td width="25px;" style="text-align:right;"><a href="/staffcp/<?=$dataModel_emails->getModelName();?>/delete/?<?=$indexField_emails;?>=<?=$row[$indexField_emails];?>" onclick="return confirm('<?=$translates['admin.main.confirm']?>');"><img title="<?=$translates['admin.main.delete']?>" border="0" src="/staffcp/media/images/trash_16.png"/></a></td>
			<?}?>
			
			<?} else {?>
			<td width="100" align="center"><i><?=$translates['admin.main.deny']?></i></td>
			<td width="50" align="center"><i><?=$translates['admin.main.deny']?></i></td>
			<?}?>
		</tr>
	<?}?>
	</tbody>
</table>