<style>
.page_wrapper { background: url('<?=HTTP_ROOT?>/static/images/background-primary.jpg')  no-repeat center center fixed;  -webkit-background-size: cover; -moz-background-size: cover; -o-background-size: cover; background-size: cover;}
</style>
<div class="container">
    <? /*   
   <ul class="breadcrumbs">
        <li>
            <?=$bread?>
        </li>
    </ul>
	
	*/ 
	
	// $name = $page['name_'.$curlang];
		if (!isset($page['name_'.$curlang]))
			$name = $page['name'];
		else
			$name = $page['name_'.$curlang];
	
	// $content = $page['content_'.$curlang];
		if (!isset($page['content_'.$curlang]))
			$content = $page['content'];
		else
			$content = $page['content_'.$curlang];
	?>
    <div class="row">
        <main class="col-md-12 col-sm-12">
            <h1><?=$name?></h1>
            <div class="theme_box clearfix">
                <?=$content?>
            </div>
        </main>
    </div> 
</div>