<script type="text/javascript">
jQuery(document).ready(function(){
	$("#singleBirdRemote").focus().autocomplete("/staffcp/accounts/search/", {
		width: 500,
		selectFirst: false
	});
	$("#singleBirdRemote").result(function(event, data, formatted) {
		location = '/staffcp/accounts/?search_id='+data[1];
	});
});
</script>
<div class="bread block">
	<label><b>Быстрый поиск клиента (контрагента):</b></label>
	<input type="text" id="singleBirdRemote" class="iput" style="width:50%;"/>
</div>