<div class="parent-menu">
<div class="menu-title" style="position:relative;width:100%;">
	<div class="menu-left" style="position:relative;width:100%;">
		<div class="menu-right" style="position:relative;width:100%;">
		
			<div class="up-menu">
				<a href="/staffcp/index/crm_list_orders/" class="btn btn-blue">Все заказы <span class="cc-alarm"><?=$fullOrderCCNew?></span>(<?=$fullOrderCCOther?>)</a>
				<a href="/staffcp/accounts/" class="btn btn-blue">Заказ на клиента</a>
				<a href="/staffcp/index/shopping/?client=false" class="btn btn-blue">Заказ без клиента</a>
				<a href="/staffcp/index/fastorder/" class="btn btn-green form-action">Быстрый заказ</a>
			</div>
			<div class="user-office">Welcome, <?=$officeData['user_name']?>!</div>
			
			<div class="titles header-a" style="text-align:right;">
				<span><img align="absmiddle" src="/staffcp/media/images/wand.png"/> <a href="/staffcp/" style="color:#FFF;">Главная</a></span>
				<span><img align="absmiddle" src="/staffcp/media/images/eye.png"/> <a target="_blank" href="/" style="color:#FFF;"><?=$translates['admin.goview']?></a></span>
				<span class="last"><img align="absmiddle" src="/staffcp/media/images/cancel.png"/> <a href="/staffcp/security/logout" style="color:#FFF;"><?=$translates['admin.exit']?></a></span>
			</div>
		</div>
	</div>
</div>
</div>