<?php $this->block('elements/banners');?>
<?php $this->block("elements/product");?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?=$_seo['title']?></title>
<meta name="description" content="<?=$_seo['descr']?>" />
<meta name="keywords" content="<?=$_seo['kwords']?>" />
<meta name="robots" content="index,follow" />


<meta http-equiv="cache-control" content="max-age=0" />
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="expires" content="0" />
<meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
<meta http-equiv="pragma" content="no-cache" />


<?php if ($favicon){?><link rel="shortcut icon" href="<?=HTTP_ROOT?>/media/files/settings/<?=$favicon?>?version=<?=VERSION?>"/><?php }?>

<?php $this->block("elements/header-css");?>

<?=$analytics?> 
<?=$header?>

<link rel="stylesheet" href="<?=HTTP_ROOT?>/media-templates/css/style.css?v=<?php echo time(); ?>" type="text/css" media="screen" />
<link rel="stylesheet" href="<?=HTTP_ROOT?>/css/cars.css" type="text/css" media="screen" />

