<!-- == Brands == -->
<div id="main_brands">
	<h3 class="uppercase title_fly"><span>Бренды</span> <a class="all_info" href="<?=HTTP_ROOT?>/brand/">все бренды</a> </h3>
	
	<div id="brands_carusel_block">
		<ul id="brands_carusel">
			<li><a href=""><img src="/media-templates/bg_img/brands_carusel/img_br_1.jpg" alt=""></a></li>
			<li><a href=""><img src="/media-templates/bg_img/brands_carusel/img_br_2.jpg" alt=""></a></li>
			<li><a href=""><img src="/media-templates/bg_img/brands_carusel/img_br_3.jpg" alt=""></a></li>
			<li><a href=""><img src="/media-templates/bg_img/brands_carusel/img_br_4.jpg" alt=""></a></li>
			
			<li><a href=""><img src="/media-templates/bg_img/brands_carusel/img_br_5.jpg" alt=""></a></li>
			<li><a href=""><img src="/media-templates/bg_img/brands_carusel/img_br_6.jpg" alt=""></a></li>
			<li><a href=""><img src="/media-templates/bg_img/brands_carusel/img_br_7.jpg" alt=""></a></li>
			<li><a href=""><img src="/media-templates/bg_img/brands_carusel/img_br_8.jpg" alt=""></a></li>
		
			<li><a href=""><img src="/media-templates/bg_img/brands_carusel/img_br_9.jpg" alt=""></a></li>
			<li><a href=""><img src="/media-templates/bg_img/brands_carusel/img_br_10.jpg" alt=""></a></li>
			<li><a href=""><img src="/media-templates/bg_img/brands_carusel/img_br_11.jpg" alt=""></a></li>
			<li><a href=""><img src="/media-templates/bg_img/brands_carusel/img_br_12.jpg" alt=""></a></li>
			
			<li><a href=""><img src="/media-templates/bg_img/brands_carusel/img_br_9.jpg" alt=""></a></li>
			<li><a href=""><img src="/media-templates/bg_img/brands_carusel/img_br_10.jpg" alt=""></a></li>
			<li><a href=""><img src="/media-templates/bg_img/brands_carusel/img_br_11.jpg" alt=""></a></li>
			<li><a href=""><img src="/media-templates/bg_img/brands_carusel/img_br_12.jpg" alt=""></a></li>
			
			<li><a href=""><img src="/media-templates/bg_img/brands_carusel/img_br_5.jpg" alt=""></a></li>
			<li><a href=""><img src="/media-templates/bg_img/brands_carusel/img_br_6.jpg" alt=""></a></li>
			<li><a href=""><img src="/media-templates/bg_img/brands_carusel/img_br_7.jpg" alt=""></a></li>
			<li><a href=""><img src="/media-templates/bg_img/brands_carusel/img_br_8.jpg" alt=""></a></li>
			
			<li><a href=""><img src="/media-templates/bg_img/brands_carusel/img_br_1.jpg" alt=""></a></li>
			<li><a href=""><img src="/media-templates/bg_img/brands_carusel/img_br_2.jpg" alt=""></a></li>
			<li><a href=""><img src="/media-templates/bg_img/brands_carusel/img_br_3.jpg" alt=""></a></li>
			<li><a href=""><img src="/media-templates/bg_img/brands_carusel/img_br_4.jpg" alt=""></a></li>
			
		</ul>
		<a id="p_prev" class="p_btn" href="#"></a>
		<a id="p_next" class="p_btn" href="#"></a>
		
		<div class="clear"></div>
	</div>
	
	
	<div class="clear"></div>
</div>