<?php function priceCreator($i,$inPrice=0,$inBrand='',$inArticle='',$inTxt='',$inID='',$inItemName='',$importer=array(),$account=array(),$html_id='html_id_',$acl=false,$acl_isset=false,$translates=array(),$inMIN=1,$fullData=array(),$only_price=false,$inDelivery='',$maxcountbasket=false){?>
<?php 
	$curExchange = Register::get('curExchange');
	$curExchangeType = Register::get('curExchangeType');
	$outPrices = $fullData;
	$startPrice = $outPrices['startPrice']; #Закупка
	$resultPRICE = $outPrices['resultPRICE']; #Продажа
?>

<?php if ($only_price){?>
<td class="th-td-result-price box-price-view <?=($i%2)?'cell':''?> <?=($inPrice)?'td-color'.(($i%2)?2:''):''?>" valign="top" style="background:#<?=$importer['color']?>;">
	<?php if ($resultPRICE){?>
		<span itemprop="offers" itemscope itemtype="http://schema.org/Offer">
			<span itemprop="price"><?=PriceHelper::number(($importer['currency'])?($resultPRICE*$importer['currency']/$curExchange):($resultPRICE/$curExchange),(($curExchange>1)?true:false))?></span>
			<meta itemprop="priceCurrency" content="<?=$curExchangeType?>" />
			<link itemprop="availability" href="http://schema.org/InStock"/>
		</span>
		<?php $currenciesNames = Register::get('currenciesNames');?>
		<?=$currenciesNames[$curExchangeType]?>
	<?php }?>
</td>
<?php if (isset($acl_isset) && $acl_isset){?>
<td class="th-td-result-price box-price-view <?=($i%2)?'cell':''?> <?=($inPrice)?'td-color'.(($i%2)?2:''):''?>" valign="top" style="background:#<?=$importer['color']?>;">
	<span class="err" style="display:block;">
		<?php if ($importer['currency']){?>
			<?=PriceHelper::number($startPrice*$importer['currency'],false,true)?> п/курсу<br/>
		<?php }?>
		<?=PriceHelper::universal($startPrice)?> <?=($importer['money_type']);?><br/>
		<?=$importer['name']?>
	</span>
</td>
<?php }?>
<td class="th-td-result-price-cart <?=($i%2)?'cell':''?> <?=($inPrice)?'td-color'.(($i%2)?2:''):''?>" valign="top" style="background:#<?=$importer['color']?>;">
	<div style="font-size:11px;"><a href="<?=HTTP_ROOT?>/account/signin/"><?=$translates['front.profile.enter']?></a></div>
</td>
<?php } else {?>
<td class="th-td-result-price box-price-view <?=($i%2)?'cell':''?> <?=($inPrice)?'td-color'.(($i%2)?2:''):''?>" valign="top" style="background:#<?=$importer['color']?>;">

	<span itemprop="offers" itemscope itemtype="http://schema.org/Offer">
		<span itemprop="price"><?=PriceHelper::number(($importer['currency'])?($resultPRICE*$importer['currency']/$curExchange):($resultPRICE/$curExchange),(($curExchange>1)?true:false))?></span>
		<meta itemprop="priceCurrency" content="<?=$curExchangeType?>" />
		<link itemprop="availability" href="http://schema.org/InStock"/>
	</span>
	
	<?php $currenciesNames = Register::get('currenciesNames');?>
	<?=$currenciesNames[$curExchangeType]?>
	
	<?php if ($outPrices['account_extra']){?>
	<span style="font-size:10px;">
		<br><strike><?=PriceHelper::number(($importer['currency'])?($outPrices['account_extra_without_baseprice']*$importer['currency']/$curExchange):($outPrices['account_extra_without_baseprice']/$curExchange),(($curExchange>1)?true:false))?></strike>&nbsp;(<?=$outPrices['account_extra']?>%)
	</span>
	<?php }?>
	
</td>
<?php if (isset($acl_isset) && $acl_isset){?>
<td class="th-td-result-price box-price-view <?=($i%2)?'cell':''?> <?=($inPrice)?'td-color'.(($i%2)?2:''):''?>" valign="top" style="background:#<?=$importer['color']?>;">
	<span class="err" style="display:block;">
		<?php if ($importer['currency']){?>
			<?=PriceHelper::number($startPrice*$importer['currency'],false,true)?> п/курсу<br/>
		<?php }?>
		<?=PriceHelper::universal($startPrice)?> <?=($importer['money_type']);?><br/>
		<?=$importer['name']?>
	</span>
</td>
<?php }?>
<td class="th-td-result-price-cart box-price-view <?=($i%2)?'cell':''?> <?=($inPrice)?'td-color'.(($i%2)?2:''):''?>" valign="top" style="background:#<?=$importer['color']?>;">

	<?php $randID = rand(rand(),rand());?>
	<?php $randIDPreOrder = rand(rand(),rand());?>
	
	<?php $preorderClass = '';?>
	<?php if($importer['only_preorder'] == 1){?>
		<?php $preorderClass = 'no-display';?>
		
		<center><a class="order-preorder" href="#" onclick="$('#preOrderCheckbox-<?=$randID?>').toggle();$(this).remove();return false;">купить под заказ</a></center>
		<div class="no-display" id="preOrderCheckbox-<?=$randID?>" style="width:75px;">
			<input type="checkbox" name="preO<?=$randID?>" id="preO<?=$randID?>" onclick="$('#pre-<?=$randID?>').toggle();"> <a href="<?=HTTP_ROOT?>/pre-order-rules/?ajax" class="order-preorder fancy_inline" style="font-size:11px;font-weight:normal;">согласен с условиями заказа</a>
		</div>
		
	<?php }?>

	<div class="<?=$preorderClass?>" id="pre-<?=$randID?>">
		<input type="hidden" name="item_min[]" id="cart_item_min_<?=$inID?>" value="<?=($inMIN)?$inMIN:1?>"/>
		<?php $maxcountbasket = preg_replace("/[^0-9]/", '', $maxcountbasket);?>
		<input type="text" name="item[]" id="cart_item_<?=$inID?>" value="1" class="i-cart-item" <?php if ($maxcountbasket){?>max="<?=$maxcountbasket?>"<?php }?>/>
		
		<?php $price1 = ($importer['currency'])?($resultPRICE*$importer['currency']):($resultPRICE);?>
		<?php $price2 = ($importer['currency'])?($startPrice*$importer['currency']):($startPrice);?>
		
		<a href="#" onclick="cart('<?=$inID?>','<?=$importer['id']?>','<?=($importer['code']=='account')?'account':'detail'?>','<?=PriceHelper::myceil($price1)?>','<?=CryptViewHelper::xencode(PriceHelper::myceil($price2))?>','<?=CryptViewHelper::xencode(strip_tags($inTxt))?>','<?=CryptViewHelper::xencode($inArticle)?>','<?=CryptViewHelper::xencode($inBrand)?>','<?=($inMIN)?$inMIN:1?>','<?=$inDelivery?>');noticecart('<?=$randID?>');return false;" title="<?=$translates['front.buy']?>"><img class="i-bask" src="<?=HTTP_ROOT?>/media-templates/img/ibask.gif"/></a>
		
		<div class="cart-alert" id="cart-ajax-<?=$randID?>">
			<img src="<?=HTTP_ROOT?>/media-templates/img/6-0.gif"/> <?=$translates['additemtocart']?>
		</div>
	</div>

</td>
<?php }?>

<?php if (isset($acl) && $acl){?>
<?php
$importer_discount		=	$outPrices['importer_discount'];
$margin_name			=	$outPrices['margin_name'];
$extra					=	$outPrices['extra'];

$extraBrand_brand_name	=	$outPrices['extraBrand_brand_name'];
$extraBrand_margin		=	$outPrices['extraBrand_margin'];
$extraBrandVal			=	$outPrices['extraBrandVal'];
$extraBrandValExtra		=	$outPrices['extraBrandValExtra'];

$dynamicExtra_margin	=	$outPrices['dynamicExtra_margin'];
$account_extra			=	$outPrices['account_extra'];

$resultPRICE_whithout_account = $outPrices['resultPRICE_whithout_account'];
?>
<td class="th-td-result-price-acl <?=($i%2)?'cell':''?> <?=($inPrice)?'td-color'.(($i%2)?2:''):''?>" valign="top" style="background:#<?=$importer['color']?>;">

	<?php $md5Key = md5($inID.'-finance-div-'.$i);?>
	<a href="#" onclick="$('.margin-history').hide();$('#<?=$md5Key?>').toggle();return false;"><img src="<?=HTTP_ROOT?>/media-templates/img/tag_green.png"/> <?=(isset($acl) && $acl)?'<sup class="imp-sort is-absolut">'.$importer['sort'].'</sup>':'';?></a>
	<div id="<?=$md5Key?>" class="margins-alert no-display margin-history">
		<a class="f-right no-dotted" onclick="$('#<?=$md5Key?>').hide();return false;" href="#"><img src="<?=HTTP_ROOT?>/media-templates/img/cross.png" title="admin" alt="admin"></a>
		
		<p class="wprice"><?=$translates['front.provider.code']?>: <b><?=$importer['name']?></b></p>
		<p class="wprice"><?=$translates['nacgroup']?>: <b><?=(isset($margin_name)&&$margin_name)?$margin_name:'нет'?></b></p>
		<p class="wprice">
			<?=$translates['front.price']?>: <?=$importer['name']?><br/>
			<b><?=$inPrice?> = <?=PriceHelper::number($inPrice*$importer['currency'],false,true)?></b>.
		</p>
		
		<?php if ($extraBrandVal){?>
			<?#brand?>
			<p class="wprice">
				<?=$translates['skidkabrand']?>: <?=($extraBrand_margin)?($extraBrand_brand_name.' '.$extraBrand_margin):0?>%.<br/>
				<b><?=$startPrice?> = <?=PriceHelper::number($startPrice*$importer['currency'],false,true)?></b>.
			</p>
		<?php }elseif ($importer_discount){?>
			<?#importer?>
			<p class="wprice">
				<?=$translates['skidkapostav']?>: <?=($importer_discount)?$importer_discount:0?>%.<br/>
				<b><?=$startPrice?> = <?=PriceHelper::number($startPrice*$importer['currency'],false,true)?></b>.
			</p>
		<?php }?>

		<?php if ($extraBrandValExtra){?>
		<p class="wprice">
			<?=$translates['front.margin.brand']?>: <?=($extraBrandValExtra)?$extraBrandValExtra:0?>%.<br/>
			<b><?=$resultPRICE_whithout_account?> = <?=PriceHelper::number($resultPRICE_whithout_account*$importer['currency'],false,true)?></b>.
		</p>
		<?php }elseif ($dynamicExtra_margin){?>
		<p class="wprice">
			<?=$translates['front.margin.period']?>: <?=($dynamicExtra_margin)?$dynamicExtra_margin:0?>%.<br/>
			<b><?=$resultPRICE_whithout_account?> = <?=PriceHelper::number($resultPRICE_whithout_account*$importer['currency'],false,true)?></b>.
		</p>
		<?php }elseif ($extra){?>
		<p class="wprice">
			<?=$translates['generalnac']?>: <?=($extra)?$extra:0?>%.<br/>
			<b><?=$resultPRICE_whithout_account?> = <?=PriceHelper::number($resultPRICE_whithout_account*$importer['currency'],false,true)?></b>.
		</p>
		<?php }?>
		
		<?php if ($account_extra){?>
		<p class="wprice">
			<?=$translates['skidkanacuser']?>: <?=($account_extra)?$account_extra:0?>%.<br/>
			<b><?=$resultPRICE?> = <?=PriceHelper::number($resultPRICE*$importer['currency'],false,true)?></b>.
		</p>
		<?php }?>
		
		<p class="wprice"><b><?=$translates['front.curr.name']?> <?=$importer['currecyName']?></b>: <?=$importer['currency']?></p>
		<p class="wprice"><b>Сортировка</b>: <?=$importer['sort']?></p>
	</div>
	
</td>
<?php }?>
<?php }?>
<?php 
function sortDoLinkJs($sort='',$func=''){
	if ($func == 'looksorting') {
		$url = $_SERVER['REQUEST_URI'];
		$url = preg_replace("|&?sort=[A-z]+&?|", "", $url);
		$url = preg_replace("|&?ajax=true+&?|", "", $url);
		$url = preg_replace("|&?cached=[0-9]+&?|", "", $url);
		return "looksorting('".$url."','".$sort."');return false;";
	}
	else {
		$url = $_SERVER['REQUEST_URI'];
		$url = str_replace("?","", preg_replace("|&?sort=[A-z]+&?|", "", $url));
		$url = str_replace("?","", preg_replace("|&?cached=[0-9]+&?|", "", $url));
		$url = str_replace("?","", preg_replace("|&?node=[0-9]+&?|", "", $url));
		$url .= (strpos($uri, "?") !== false)?"&":"?";
		return "looksortingcatalog('".$url."','".$sort."');return false;";
	}
}
?>
<?php function viewer_header($translates,$fieldFR,$acl_isset,$acl,$disableSort=false,$linkCatalog=false){

	$fields_importer = Register::get('mode_view_fields_importer');
	$curExchangeType = Register::get('curExchangeType');
	$sSortPriceView = Register::get('sSortPriceView');
	
	if ($linkCatalog) {
		$sortFunction = 'looksortingcatalog';
	} else {
		$sortFunction = 'looksorting';
	} 
	/*	
?>
	<tr>
		<th style="width:25px;">
			<?php if (Register::get('__cached_status')){?>
			<img src="/media-templates/icons/cup.png" alt="Кеш запрос" title="Кеш запрос"/>
			<?php }?>
		</th>
        <th class="th-td-result-brand">
        <?php if ($disableSort) {?>
        	<?=$translates['front.brand']?>
        <?php }else{?>
        	<a href="#" onclick="<?=sortDoLinkJs('brand',$sortFunction);?>" class="ssort sort_<?=($sSortPriceView=='brand')?'asc':'all'?>"><span><?=$translates['front.brand']?></span></a>
        <?php }?>
        </th>
	    <th class="th-td-result-article">
		<?php if ($disableSort) {?>
	    	<?=$translates['front.article']?>
	    <?php }else{?>
	    	<a href="#" onclick="<?=sortDoLinkJs('article',$sortFunction);?>" class="ssort sort_<?=($sSortPriceView=='article')?'asc':'all'?>"><span><?=$translates['front.article']?></span></a>
	    <?php }?>
	    </th>
	    <th class="th-td-result-descr"><?=$translates['front.descr']?></th>
	    
	    <?php if ($fields_importer){?>
	    <th class="th-td-result-place"><?=$translates['naprav']?></th>
	    <?php }?>
	    
	    <th class="th-td-result-box"><?=$translates['front.search.box']?></th>
	    <th class="th-td-result-delivery">
	    <?php if ($disableSort) {?>
	    	Срок
	    <?php }else{?>
	    	<a href="#" onclick="<?=sortDoLinkJs('delivery',$sortFunction);?>" class="ssort sort_<?=($sSortPriceView=='delivery')?'asc':'all'?>"><span>Срок</span></a>
	    <?php }?>
	    </th>
	    <th class="th-td-result-price<?=($acl_isset)?'-acl-isset':''?>">
	    
	    	<?php if (!$disableSort) {?>
	    	<a href="#" onclick="<?=sortDoLinkJs((($sSortPriceView=='min')?'max':'min'),$sortFunction);?>" class="ssort sort_<?=($sSortPriceView=='min')?'asc':''?><?=($sSortPriceView=='max')?'desc':''?><?=($sSortPriceView!='max'&&$sSortPriceView!='min')?'all':''?>">
	    	<?php }?>
	    	
	    	<?php $currenciesNames = Register::get('currenciesNames');?>
	    	<span><?=$translates['front.price']?>&nbsp;(<?=$currenciesNames[$curExchangeType]?>)</span>
	    	
			<?php if (!$disableSort) {?></a><?php }?>
	    </th>
	    <?php if($acl_isset){?><th class="th-td-result-price<?=($acl_isset)?'-acl-isset':''?>">Закупка</th><?php }?>
	    <th class="th-td-result-price-cart"></th>
	    <?php if($acl){?><th class="th-td-result-price-acl"></th><?php }?>
    </tr>
<?php*/  } ?>
<?php function viewer($i,$data,$acl,$currency,$account,$imgdescr=true,$translates,$html_id,$acl_isset,$fieldFR=0,$wbs_redirect=false,$hide_tr=false,$hide_count=false,$iterreset=0){?>
<?php
	$fields_importer = Register::get('mode_view_fields_importer');
	 
	$lamp_search_notes_exist = Register::get('lamp_search_notes_exist');
	$LAC_COLOR_SET = Register::get('LAC_COLOR_SET');
	$mode_view_articles = Register::get('mode_view_articles');
	$mode_view_articles = ($account)?0:$mode_view_articles;
	$importer = (isset($data['MY_PRICE']['IMPORTER_DATA'])?$data['MY_PRICE']['IMPORTER_DATA']:array());
?>

<tr class="<?=($hide_tr)?'htg_':'';?><?=strtoupper(FuncModel::stringfilter($data['SUP_BRAND']))?>_<?=FuncModel::stringfilter($data['ART_ARTICLE_NR'])?><?=(!$hide_count)?'_toggle':''?> <?=($hide_tr)?'hide_item_search_minimazi':'';?> <?=(is_string($iterreset)&&$iterreset=='delimiter')?'hite_item_styled':''?>">

	<?/* BRAND */?>
	<td class="<?=($i%2)?'cell':''?> <?=(isset($data['DB_PRICE'])&&$data['DB_PRICE'])?'td-color'.(($i%2)?2:''):''?>" style="background:#<?=$importer['color']?>;">
		<?php if ($hide_count){?>
			<span title="Показать еще <?=$hide_count?> предложен<?=(($hide_count==1)?'ие':(in_array($hide_count,array(2,3,4))?'ия':(($hide_count > 3)?'ий':'')))?>" class="viewer-box" onclick="group_result_search(this,'htg_<?=strtoupper(FuncModel::stringfilter($data['SUP_BRAND']))?>_<?=FuncModel::stringfilter($data['ART_ARTICLE_NR'])?>');return false;">+<?=$hide_count?></span>
	    <?php }?>
	</td>
    <td class="th-td-result-brand <?=($i%2)?'cell':''?> <?=(isset($data['DB_PRICE'])&&$data['DB_PRICE'])?'td-color'.(($i%2)?2:''):''?> <?//=($hide_count)?'':'hc-pd';?>" style="background:#<?=$importer['color']?>;">
	    <span class="<?=($hide_tr)?'no-display':''?> <?=(isset($LAC_COLOR_SET)&&in_array(FuncModel::stringfilter($data['ART_ARTICLE_NR']),$LAC_COLOR_SET))?'SET_LAC_COLOR':''?>">
	    	<b><a class="fancy_inline droppeda" href="<?=HTTP_ROOT?>/brand/ajax/<?=urlencode(str_replace("+","~plus~",strtoupper($data['SUP_BRAND'])))?>/"><?=strtoupper($data['SUP_BRAND'])?></a></b>
	    </span>
    </td>

    <?/* ARTICLE */?>
    <td class="th-td-result-article <?=($i%2)?'cell':''?> <?=(isset($data['DB_PRICE'])&&$data['DB_PRICE'])?'td-color'.(($i%2)?2:''):''?>" style="background:#<?=$importer['color']?>;">
    <span class="<?=($hide_tr)?'no-display':''?>">
    	
	    <span class="<?=(isset($LAC_COLOR_SET)&&in_array(FuncModel::stringfilter($data['ART_ARTICLE_NR']),$LAC_COLOR_SET))?'SET_LAC_COLOR':''?>">
	    <?php if (isset($data['ART_ID']) && $data['ART_ID']){?>
	    	<b>
	    		<?php if (isset($imgdescr) && $imgdescr && !$mode_view_articles){?>
	    			<a class="ared" href="<?=HTTP_ROOT?>/detail/<?=$data['ART_ID']?>/"><?=$data['ART_ARTICLE_NR']?></a>
	    		<?php }else{?>
	    			<?=(($mode_view_articles)?HidestartsViewHelper::hide($data['ART_ARTICLE_NR']):$data['ART_ARTICLE_NR']);?>
	    		<?php }?>
	    	</b>
	    <?php } else {?>
	    	<b><?=(($mode_view_articles)?HidestartsViewHelper::hide($data['ART_ARTICLE_NR']):$data['ART_ARTICLE_NR']);?></b>
	    <?php }?>
	    </span>
	    
    </span>
    </td>
    
    <?/* DESCR */?>
    <td class="th-td-result-descr <?=($i%2)?'cell':''?> <?=(isset($data['DB_PRICE'])&&$data['DB_PRICE'])?'td-color'.(($i%2)?2:''):''?>" style="background:#<?=$importer['color']?>;">
    <?//php if(!$hide_tr){?>
    	<span class="artlook-descr">
    	<?php $msg = (isset($data['TEX_TEXT']))?$data['TEX_TEXT']:(isset($data['DB_DESCR'])?$data['DB_DESCR']:'');?>
    	<span class="descr-hide-overflow" style="<?=(mb_strlen($msg,'utf8')>100)?'width:150px;':''?>">
    		<?=$msg?>
	    	<?/* INSTALL */?>
		    <?php if (isset($fieldFR) && $fieldFR > 1){?>
				<?php $FR = $data['FR'];?>
				<?=(isset($FR['front']) && $FR['front']==1)?'передний мост':'';?>
				<?=(isset($FR['rear']) && $FR['rear']==1)?'задний мост':'';?>
		    <?php }?>
	    </span>
    	
    	
		
		</span>
		
		<?php if ((isset($data['CRITERIA'])&&count($data['CRITERIA'])>0) || (isset($data['INFO'])&&count($data['INFO'])>0) || (isset($importer['info'])?strlen(trim(strip_tags($importer['info']))):0) ){?>
		<div class="no-display">
			<div id="<?=$html_id?>-info-div-<?=$i?>">
			
				<h1><?=$data['SUP_BRAND']?> <?=(($mode_view_articles)?HidestartsViewHelper::hide($data['ART_ARTICLE_NR']):$data['ART_ARTICLE_NR']);?> <?=$data['TEX_TEXT']?></h1>
	            <?php foreach ($data['CRITERIA'] as $name=>$item) {?>
	                <p><?=$item->CRITERIA_DES_TEXT?>: <?=$item->CRITERIA_VALUE_TEXT?></p>
	            <?php }?>
	            <?php if (isset($data['INFO']) && count($data['INFO'])>0){?>
	            <?php foreach ($data['INFO'] as $name=>$item) {?>
	                <p><?=$item->AIN_TMO_TEXT?></p>
	            <?php }?>
	            <?php }?>
	            
	            <?=$importer['info']?>
	            
	            <?php if ($importer['price_date_update'] >= time()){?>
	            <h2><?=$translates['zdateupdateprice']?></h2>
	            <p><b><?=($importer['price_date_update'])?date("d.m.Y",$importer['price_date_update']):date("d.m.Y")?></b></p>
	            <?php }?>
			</div>
		</div>
		<?php }?>
    <?//php }?>
    </td>

    <?/* PLACE */?>
    <?php if ($fields_importer){?>
    <td class="th-td-result-place <?=($i%2)?'cell':''?> <?=(isset($data['DB_PRICE'])&&$data['DB_PRICE'])?'td-color'.(($i%2)?2:''):''?>" style="background:#<?=$importer['color']?>;">
    	<?=(isset($importer['name_price'])?$importer['name_price']:'')?>
    </td>
    <?php }?>
    
    <?/* BOX */?>
    <td class="th-td-result-box <?=($i%2)?'cell':''?> <?=(isset($data['DB_PRICE'])&&$data['DB_PRICE'])?'td-color'.(($i%2)?2:''):''?> t-center" style="background:#<?=$importer['color']?>;"><?=(isset($data['DB_BOX']))?$data['DB_BOX']:'-'?></td>
    
    <?/* DELIVERY */?>
    <td class="th-td-result-delivery smallprice <?=($i%2)?'cell':''?> <?=(isset($data['DB_PRICE'])&&$data['DB_PRICE'])?'td-color'.(($i%2)?2:''):''?> t-center" style="background:#<?=$importer['color']?>;">
    	<?=(isset($data['DB_DELIVERY']) && $data['DB_DELIVERY'])?$data['DB_DELIVERY']:(isset($importer['delivery'])?$importer['delivery']:'');?> (дн)
    </td>
    
    <?php if (!$wbs_redirect){?>
	    
	    <?php $inPrice = (isset($data['DB_PRICE'])?$data['DB_PRICE']:0);?>
	    <?php $inBrand = (isset($data['DB_BRAND_ID'])?$data['DB_BRAND_ID']:'');?>
	    <?php $inBrandName = (isset($data['SUP_BRAND'])?$data['SUP_BRAND']:'');?>
	    <?php $inTxt = (isset($data['TEX_TEXT'])?$data['TEX_TEXT']:'');?>
	    <?php $inDelivery = (isset($data['DB_DELIVERY']) && $data['DB_DELIVERY'])?$data['DB_DELIVERY']:(isset($importer['delivery'])?$importer['delivery']:'');?>
	    <?php $inID = (isset($data['DB_ID'])?$data['DB_ID']:'');?>
	    <?php $inItemName = (isset($data['ART_ARTICLE_NR'])?$data['ART_ARTICLE_NR']:'').' '.(isset($data['SUP_BRAND'])?$data['SUP_BRAND']:'').' '.(isset($data['TEX_TEXT'])?$data['TEX_TEXT']:'');?>
	    <?php $inArticle = (isset($data['ART_ARTICLE_NR'])?$data['ART_ARTICLE_NR']:'');?>
	    <?php $inMIN = isset($data['DB_MIN'])?$data['DB_MIN']:1;?>
	    <?php $fullData = (isset($data['MY_PRICE']['OUTPRICE_DATA'])?$data['MY_PRICE']['OUTPRICE_DATA']:array());?>
	    <?php $inBOX = ((isset($data['DB_BOX']))?$data['DB_BOX']:'-');?>
    
	    <?/* ***************** PRICE ***************** */?>
	    <?php if (!$mode_view_articles){?>
		    
		    <?php if ($inPrice){?>
		    
		    	<?=priceCreator($i,$inPrice,$inBrandName,$inArticle,$inTxt,$inID,$inItemName,$importer,$account,$html_id,$acl,$acl_isset,$translates,$inMIN,$fullData,false,$inDelivery,$inBOX);?>

		    <?php }else{?>
		    
			    <td class="th-td-result-price <?=($i%2)?'cell':''?> <?=($data['DB_PRICE'])?'td-color'.(($i%2)?2:''):''?>" valign="top" style="background:#<?=$importer['color']?>;">
			    	<a href="<?=HTTP_ROOT?>/contacts/?CONTACT=<?=urlencode($inItemName)?>"><b><?=$translates['front.ask']?></b></a>
			    </td>
			    <td class="th-td-result-price-cart <?=($i%2)?'cell':''?> <?=($data['DB_PRICE'])?'td-color'.(($i%2)?2:''):''?>" valign="top" style="background:#<?=$importer['color']?>;text-align:center;"></td>
			    <?php if (isset($acl) && $acl){?>
			    <td class="th-td-result-price-acl <?=($i%2)?'cell':''?> <?=($data['DB_PRICE'])?'td-color'.(($i%2)?2:''):''?>" valign="top" style="background:#<?=$importer['color']?>;"></td>
			    <?php }?>
		    
		    <?php }?>
		    
		<?php }else{?>
		
			<?=priceCreator($i,$inPrice,$inBrandName,$inArticle,$inTxt,$inID,$inItemName,$importer,$account,$html_id,$acl,$acl_isset,$translates,$inMIN,$fullData,true);?>
				
		<?php }?>
		<?/* ***************** PRICE ***************** */?>
		
	<?php }else{?>
	
		<td class="th-td-result-price <?=($i%2)?'cell':''?> <?=($data['DB_PRICE'])?'td-color'.(($i%2)?2:''):''?>" valign="top" style="background:#<?=$importer['color']?>;text-align:center;">
			<b><a href="<?=HTTP_ROOT?>/search/number/?article=<?=$data['ART_ARTICLE_NR']?>&searchbrand=<?=urlencode($data['SUP_BRAND'])?>"><?=$translates['price_and_nal']?></a></b>
		</td>
		<td class="th-td-result-price-cart <?=($i%2)?'cell':''?> <?=($data['DB_PRICE'])?'td-color'.(($i%2)?2:''):''?>" valign="top" style="background:#<?=$importer['color']?>;text-align:center;"></td>
		<?php if (isset($acl) && $acl){?>
	    <td class="th-td-result-price-acl <?=($i%2)?'cell':''?> <?=($data['DB_PRICE'])?'td-color'.(($i%2)?2:''):''?>" valign="top" style="background:#<?=$importer['color']?>;"></td>
	    <?php }?>
	
		
	<?php }?>
	
</tr>
<?php }?>
<?php function build_tdoc_categories($tdoc_data, $td_url, $where = 'main', $img_path ){
    $data = array(); 
    $issetTree = array();
    
    foreach($tdoc_data as $st){
    	$issetTree []= $st->ID;
    	
        switch($st->ID){
            case '10105': //фильтры
                $data[$st->ID] = array(
                    'ID' => $st->ID,
                    'img' =>  $img_path.'td_m'.$st->ID.'.jpg',
                    'title' => $st->NAME,
                    'childrens' => array(
                        '10360' => array(
                            'child_id'=>10360,
                            'child_name'=>'Воздушный',
                            'child_link'=>$td_url.'/10360/'
                        ),
                        '10359' => array(
                            'child_id'=>10359,
                            'child_name'=>'Масляный',
                            'child_link'=>$td_url.'/10359/'
                        ),
                        '10361' => array(
                            'child_id'=>10361,
                            'child_name'=>'Топливный',
                            'child_link'=>$td_url.'/10361/'
                        )
                    )
                );
                break;
            case '10103': //механизм газораспределения
                $data[$st->ID] = array(
                    'ID' => $st->ID,
                    'img' => $img_path.'td_m'.$st->ID.'.jpg',
                    'title' => $st->NAME,
                    'childrens' => array(
                        '10523' => array(
                            'child_id'=>10523,
                            'child_name'=>'Клапаны',
                            'child_link'=>$td_url.'/10523/'
                        ),
                        '10504' => array(
                            'child_id'=>10504,
                            'child_name'=>'Ремень ГРМ',
                            'child_link'=>$td_url.'/10504/'
                        )
                    )
                );
                break;
            case '10182': //поликлиновый механизм
                $data[$st->ID] = array(
                    'ID' => $st->ID,
                    'img' => $img_path.'td_m'.$st->ID.'.jpg',
                    'title' => $st->NAME,
                    'childrens' => array(
                        '10535' => array(
                            'child_id'=>10535,
                            'child_name'=>'Паразитный ролик',
                            'child_link'=>$td_url.'/10535/'
                        ),
                        '10531' => array(
                            'child_id'=>10531,
                            'child_name'=>'Поликлиновый ремень',
                            'child_link'=>$td_url.'/10531/'
                        ),
                        '10534' => array(
                            'child_id'=>10534,
                            'child_name'=>'Ролик натяжителя',
                            'child_link'=>$td_url.'/10534/'
                        )
                    )
                );
                break;
            case '10726': //дисковый тормозной механизм
                $data[$st->ID] = array(
                    'ID' => $st->ID,
                    'img' => $img_path.'td_m'.$st->ID.'.jpg',
                    'title' => $st->NAME,
                    'childrens' => array(
                        '10132' => array(
                            'child_id'=>10132,
                            'child_name'=>'Тормозной диск',
                            'child_link'=>$td_url.'/10132/'
                        ),
                        '10130' => array(
                            'child_id'=>10130,
                            'child_name'=>'Тормозные колодки',
                            'child_link'=>$td_url.'/10130/'
                        )
                    )
                );
                break;
            case '10727': //барабанный тормозной механизм
                $data[$st->ID] = array(
                    'ID' => $st->ID,
                    'img' => $img_path.'td_m'.$st->ID.'.jpg',
                    'title' => $st->NAME,
                    'childrens' => array(
                        '10133' => array(
                            'child_id'=>10133,
                            'child_name'=>'Тормозной барабан',
                            'child_link'=>$td_url.'/10133/'
                        ),
                        '10131' => array(
                            'child_id'=>10131,
                            'child_name'=>'Тормозные колодки',
                            'child_link'=>$td_url.'/10131/'
                        )
                    )
                );
                break;
            case '10111': //амортизаторы
                $data[$st->ID] = array(
                    'ID' => $st->ID,
                    'img' => $img_path.'td_m'.$st->ID.'.jpg',
                    'title' => $st->NAME,
                    'childrens' => array(
                        '10221' => array(
                            'child_id'=>10221,
                            'child_name'=>'Амортизатор',
                            'child_link'=>$td_url.'/10221/'
                        ),
                        '10213' => array(
                            'child_id'=>10213,
                            'child_name'=>'Пружины',
                            'child_link'=>$td_url.'/10213/'
                        )
                    )
                );
                break;
            case '10113': //подвеска
                $data[$st->ID] = array(
                    'ID' => $st->ID,
                    'img' => $img_path.'td_m'.$st->ID.'.jpg',
                    'title' => $st->NAME,
                    'childrens' => array(
                        '10313' => array(
                            'child_id'=>10313,
                            'child_name'=>'Крепление колеса',
                            'child_link'=>$td_url.'/10313/'
                        ),
                        '10678' => array(
                            'child_id'=>10678,
                            'child_name'=>'Ступица колеса',
                            'child_link'=>$td_url.'/10678/'
                        ),
                        '10681' => array(
                            'child_id'=>10681,
                            'child_name'=>'Шарнир независимой подвески',
                            'child_link'=>$td_url.'/10681/'
                        )
                    )
                );
                break;
            case '10310': //Стабилизатор
                $data[$st->ID] = array(
                    'ID' => $st->ID,
                    'img' => $img_path.'td_m'.$st->ID.'.jpg',
                    'title' => $st->NAME,
                    'childrens' => array(
                        '10677' => array(
                            'child_id'=>10677,
                            'child_name'=>'Соединительная тяга',
                            'child_link'=>$td_url.'/10677/'
                        ),
                        '10673' => array(
                            'child_id'=>10673,
                            'child_name'=>'Стабилизатор',
                            'child_link'=>$td_url.'/10673/'
                        ),
                        '10690' => array(
                            'child_id'=>10690,
                            'child_name'=>'Стойка стабилизатора',
                            'child_link'=>$td_url.'/10690/'
                        )
                    )
                );
                break;
            case '10112': //рулевое управление
                $data[$st->ID] = array(
                    'ID' => $st->ID,
                    'img' => $img_path.'td_m'.$st->ID.'.jpg',
                    'title' => $st->NAME,
                    'childrens' => array(
                        '10301' => array(
                            'child_id'=>10301,
                            'child_name'=>'Кожух/прокладки',
                            'child_link'=>$td_url.'/10301/'
                        ),
                        '10297' => array(
                            'child_id'=>10297,
                            'child_name'=>'Рулевая тяга',
                            'child_link'=>$td_url.'/10297/'
                        ),
                        '10299' => array(
                            'child_id'=>10299,
                            'child_name'=>'Рулевой механизм',
                            'child_link'=>$td_url.'/10299/'
                        )
                    )
                );
                break;
            case '10313': //колесо
                $data[$st->ID] = array(
                    'ID' => $st->ID,
                    'img' => $img_path.'td_m'.$st->ID.'.jpg',
                    'title' => $st->NAME,
                    'childrens' => array(
                        '10679' => array(
                            'child_id'=>10679,
                            'child_name'=>'Подшипник',
                            'child_link'=>$td_url.'/10679/'
                        ),
                        '10678' => array(
                            'child_id'=>10678,
                            'child_name'=>'Ступица',
                            'child_link'=>$td_url.'/10678/'
                        )
                    )
                );
                break;
            case '10114': //рулевое управление
                $data[$st->ID] = array(
                    'ID' => $st->ID,
                    'img' => $img_path.'td_m'.$st->ID.'.jpg',
                    'title' => $st->NAME,
                    'childrens' => array(
                        '10171' => array(
                            'child_id'=>10171,
                            'child_name'=>'ШРУС',
                            'child_link'=>$td_url.'/10171/'
                        ),
                        '10162' => array(
                            'child_id'=>10162,
                            'child_name'=>'Приводной вал',
                            'child_link'=>$td_url.'/10162/'
                        ),
                        '10174' => array(
                            'child_id'=>10174,
                            'child_name'=>'Пыльник',
                            'child_link'=>$td_url.'/10174/'
                        )
                    )
                );
                break;
            case '10150': //сцепление
                $data[$st->ID] = array(
                    'ID' => $st->ID,
                    'img' => $img_path.'td_m'.$st->ID.'.jpg',
                    'title' => $st->NAME,
                    'childrens' => array(
                        '10153' => array(
                            'child_id'=>10153,
                            'child_name'=>'Диск сцепления',
                            'child_link'=>$td_url.'/10153/'
                        ),
                        '10152' => array(
                            'child_id'=>10152,
                            'child_name'=>'Нажимной диск',
                            'child_link'=>$td_url.'/10152/'
                        ),
                        '10151' => array(
                            'child_id'=>10151,
                            'child_name'=>'Комплект сцепления',
                            'child_link'=>$td_url.'/10151/'
                        )
                    )
                );
                break;
            case '10110': //электрика
                $data[$st->ID] = array(
                    'ID' => $st->ID,
                    'img' => $img_path.'td_m'.$st->ID.'.jpg',
                    'title' => $st->NAME,
                    'childrens' => array(
                        '10450' => array(
                            'child_id'=>10450,
                            'child_name'=>'Генератор',
                            'child_link'=>$td_url.'/10450/'
                        ),
                        '10459' => array(
                            'child_id'=>10459,
                            'child_name'=>'Стартер',
                            'child_link'=>$td_url.'/10459/'
                        )
                    )
                );
                break;
            case '10108': //зажигание
                $data[$st->ID] = array(
                    'ID' => $st->ID,
                    'img' => $img_path.'td_m'.$st->ID.'.jpg',
                    'title' => $st->NAME,
                    'childrens' => array(
                        '10251' => array(
                            'child_id'=>10251,
                            'child_name'=>'Свеча зажигания',
                            'child_link'=>$td_url.'/10251/'
                        ),
                        '10253' => array(
                            'child_id'=>10253,
                            'child_name'=>'Кабели',
                            'child_link'=>$td_url.'/10253/'
                        )
                    )
                );
                break;
            case '10104': //система выпуска
                $data[$st->ID] = array(
                    'ID' => $st->ID,
                    'img' => $img_path.'td_m'.$st->ID.'.jpg',
                    'title' => $st->NAME,
                    'childrens' => array(
                        '13514' => array(
                            'child_id'=>13514,
                            'child_name'=>'Датчики',
                            'child_link'=>$td_url.'/13514/'
                        ),
                        '10148' => array(
                            'child_id'=>10148,
                            'child_name'=>'Лямбда-зонд',
                            'child_link'=>$td_url.'/10148/'
                        )
                    )
                );
                break;
            case '10354': //приготовление смеси
                $data[$st->ID] = array(
                    'ID' => $st->ID,
                    'img' => $img_path.'td_m'.$st->ID.'.jpg',
                    'title' => $st->NAME,
                    'childrens' => array(
                        '12899' => array(
                            'child_id'=>12899,
                            'child_name'=>'Форсунка',
                            'child_link'=>$td_url.'/12899/'
                        )
                    )
                );
                break;
            case '10635': //крепление двигателя
                $data[$st->ID] = array(
                    'ID' => $st->ID,
                    'img' => $img_path.'td_m'.$st->ID.'.jpg',
                    'title' => $st->NAME,
                    'childrens' => array(
                        '10636' => array(
                            'child_id'=>10636,
                            'child_name'=>'Кронштейн',
                            'child_link'=>$td_url.'/10636/'
                        ),
                        '10639' => array(
                            'child_id'=>10639,
                            'child_name'=>'Отбойник',
                            'child_link'=>$td_url.'/10639/'
                        ),
                        '10638' => array(
                            'child_id'=>10638,
                            'child_name'=>'Подвеска',
                            'child_link'=>$td_url.'/10638/'
                        )
                    )
                );
                break;
            case '10620': //поршень
                $data[$st->ID] = array(
                    'ID' => $st->ID,
                    'img' => $img_path.'td_m'.$st->ID.'.jpg',
                    'title' => $st->NAME,
                    'childrens' => array(
                        '10631' => array(
                            'child_id'=>10631,
                            'child_name'=>'Кольца',
                            'child_link'=>$td_url.'/10631/'
                        ),
                        '10629' => array(
                            'child_id'=>10629,
                            'child_name'=>'Поршень',
                            'child_link'=>$td_url.'/10629/'
                        )
                    )
                );
                break;
            case '10118': //Стеклоочиститель
                $data[$st->ID] = array(
                    'ID' => $st->ID,
                    'img' => $img_path.'td_m'.$st->ID.'.jpg',
                    'title' => $st->NAME,
                    'childrens' => array(
                        '10233' => array(
                            'child_id'=>10233,
                            'child_name'=>'Стеклоочиститель',
                            'child_link'=>$td_url.'/10233/'
                        )
                    )
                );
                break;
        }
    }
    ?>
    <?php if($where == 'main'){ //если нужно меню для контента ?>
        <?php if(count($data)>0){?>
            <div class="tdoc-categories">
            <?php foreach($data as $tdoc_cat){?>
            
            	<?php $viewitem = false;?>
            	<?php foreach($tdoc_cat['childrens'] as $child){ ?>
            	<?php if (in_array($child['child_id'], $issetTree)){?>
            		<?php $viewitem = true;?>
            	<?php }?>
            	<?php }?>
            	
            	<?php if ($viewitem){?>
                <div class="tdoc_cat">
                    <div class="tdoc_img"><img src="<?=$tdoc_cat['img'];?>" title="<?=$tdoc_cat['title'];?>" alt="<?=$tdoc_cat['title'];?>" class="img-responsive"></div>
                    <div class="tdoc_info">
                        <div class="tdoc_title"><?=FunctionsViewHelper::mb_ucfirst($tdoc_cat['title']);?></div>
                        <div class="tdoc_childrens">
                        <?php if(count($tdoc_cat['childrens'])>0){?>
                        <ul>
                            <?php foreach($tdoc_cat['childrens'] as $child){ ?>
                            <?php if (in_array($child['child_id'], $issetTree)){?>
                                <li data_id="<?=$child['child_id'];?>"><a href="<?=$child['child_link'];?>"><?php echo $child['child_name']; ?></a></li>
							<?php }?>
                            <?php }?>
                        </ul>
                        <?php }?>
                        </div>
                    </div>
                </div>
                <?php }?>
                
            <?php }?>
            </div>
        <?php }?>
    <?php } elseif($where == 'left'){ //если нужно меню для левой колонки ?>
        <?php if(count($data) > 0){?>
            <div class="tdoc_menu_left">
                <div class="title">Каталог</div>
                <div class="tml">
                    <ul>
                    <?php foreach($data as $tdoc_cat){?>
                    <li class="tdoc_cat_li">
                        <div class="tdoc_title"><a href="javascript:void(0);"><?=$tdoc_cat['title'];?></a></div>
                        <?php if(count($tdoc_cat['childrens'])>0){?>
                            <div class="tdoc_childrens">
                                    <ul>
                                        <?php foreach($tdoc_cat['childrens'] as $child){ ?>
                                            <li data_id="<?=$child['child_id'];?>"><a href="<?=$child['child_link'];?>"><?php echo $child['child_name']; ?></a></li>
                                        <?php } ?>
                                    </ul>
                            </div>
                        <?php }?>
                    </li>
                    <?php }?>
                    </ul>
                </div>
            </div>
        <?php }?>
    <?php }?>
<?php }?>