<div id="notice" style="margin-top:10px;">
	<div class="post z-index-1" style="margin:0px;">
		<div>
			<a href="<?=HTTP_ROOT?>/" onclick="$('#notice').hide();return false;" class="f-right"><img alt="admin" title="admin" src="<?=HTTP_ROOT?>/media-templates/img/cross.png"/></a>
			<p><a href="http://www.ryli.by/" class="h1 black top-10">Ryli.by / Demo view</a></p>
			<p><?=$translates['front.notice']?></p>
			<p><a href="http://www.new.by/spareparts/"><?=$translates['doneproejctalert']?></a></p>
		</div>
	</div>
</div>