<table width="100%" style="border:solid 1px #dadada;border-radius:5px;padding:5px;">
<tr>
	<td>
		<p style="padding:4px 5px;margin:0px;"><b>Доступные обработчики прайсов</b></p>
		<?/*
		<div class="index_lnks"><a href="/staffcp/db_parsers/shatem/"><span><img align="absmiddle" src="/staffcp/media/images/wand.png"> Шате-М</span></a></div>
		<div class="index_lnks"><a href="/staffcp/db_parsers/asmetal/"><span><img align="absmiddle" src="/staffcp/media/images/wand.png"> AsMetal</span></a></div>
		<div class="index_lnks"><a href="/staffcp/db_parsers/ngorod/"><span><img align="absmiddle" src="/staffcp/media/images/wand.png"> Ngorod</span></a></div>
		<div class="index_lnks"><a href="/staffcp/db_parsers/motex/"><span><img align="absmiddle" src="/staffcp/media/images/wand.png"> MOTEX</span></a></div>
		*/?>
		<div class="index_lnks"><a href="/staffcp/db_parsers/originals/"><span><img align="absmiddle" src="/staffcp/media/images/wand.png"> Originals (Группы)</span></a></div>
		
	</td>
</tr>
</table>