<style>
.cart-filters {}
</style>
<h1 class="h1-header">Искать/Сортировать</h1>
<form method="GET" action="/staffcp/index/crm_list_orders/">
<table style="margin:0 auto;width:100%;" class="ss cart-filters">
<tr>
	<td style="width:100px;"><b>по номеру заказа</b></td>
	<td style="width:400px;" class="tdbrd"><input type="text" name="search[number]" value="<?=(isset($search['number'])&&$search['number'])?$search['number']:'';?>" class="iput"/></td>
	
	<td style="width:200px;"><b>по клиенту (ID клиента)</b></td>
	<td class="tdbrd">
		<script type="text/javascript">
		$(document).ready(function() {
			var akey = new Array();
			<?php $str = '';?>
			<?php if (isset($accountsList) && count($accountsList)>0){?>
			<?php foreach ($accountsList as $account){?>
				<?php $str .= '"'.addslashes($account['id'].' - '.$account['name'].' '.$account['email'].' '.$account['phones']).'"'.(($i!=count($account))?',':'');?>
				akey[<?='"'.addslashes($account['id'].' - '.$account['name'].' '.$account['email'].' '.$account['phones']).'"'?>]= <?=$account['id']?>;
			<?php }?>
			<?php }?>
			var str = [<?=$str?>];
			$(".auto-searcher").focus().autocomplete(str, {
				matchContains: true,
				minChars: 0
			});
			function treeviewer(event, data, formatted) {
				$('#set_account_id').val(akey[formatted]);
			}
			$(".auto-searcher").result(treeviewer);
		});
		</script>
		<input type="text" name="search[account_id]" class="iput auto-searcher" id="set_account_id" value="<?=(isset($search)&&$search['account_id'])?$search['account_id']:''?>"/>
	</td>
	
	<td width="100px"><b>по менеджеру</b></td>
	<td class="tdbrd">
	<select name="search[manager_id]" class="iput"  style="width:100%;">
		<option value=""></option>
		<?php if (isset($managers) && count($managers)>0){?>
		<?php reset($managers); foreach ($managers as $manager){?>
		<option value="<?=$manager['id']?>" <?=(isset($search['manager_id']) && $search['manager_id'] == $manager['id'])?'selected':'';?>><?=$manager['name']?> (<?=$manager['city']?> / <?=$manager['office']?>)</option>
		<?php }?>
		<?php }?>
	</select>
	</td>
</tr>
<tr>
	
	<td width="100px"><b>по дате</b></td>
	<td class="tdbrd">
		<b>c</b>&nbsp;<input type="text" name="search[dt_from]" id="2dt_from" value="<?=(isset($search['dt_from'])&&$search['dt_from'])?$search['dt_from']:'';?>" class="iput" style="width:100px;"/>
		<input type="button" id="2dt_from_picker" value="&raquo;" class="btn">
		<b>по</b>&nbsp;<input type="text" name="search[dt_to]" id="2dt_to" value="<?=(isset($search['dt_to'])&&$search['dt_to'])?$search['dt_to']:'';?>" class="iput" style="width:100px;"/>
		<input type="button" id="2dt_to_picker" value="&raquo;" class="btn">
		<script type="text/javascript">
		$(document).ready(function() {
			Calendar.setup({inputField: '2dt_from',button: '2dt_from_picker',date: '<?=(isset($search['dt_from']) && $search['dt_from'])?$search['dt_from']:date('d.m.Y')?>'});
			Calendar.setup({inputField: '2dt_from',button: '2dt_from',date: '<?=(isset($search['dt_from']) && $search['dt_from'])?$search['dt_from']:date('d.m.Y')?>',eventName: 'focus'});
			Calendar.setup({inputField: '2dt_to',button: '2dt_to_picker',date: '<?=(isset($search['dt_to']) && $search['dt_to'])?$search['dt_to']:date('d.m.Y')?>'});
			Calendar.setup({inputField: '2dt_to',button: '2dt_to',date: '<?=(isset($search['dt_to']) && $search['dt_to'])?$search['dt_to']:date('d.m.Y')?>',eventName: 'focus'});
		});
		</script>
	</td>
	
	<td width="100px"><b>по статусу</b></td>
	<td class="tdbrd" style="font-size:10px !important;width:200px;">
		<select name="search[status]" class="iput"  style="width:100%;">
			<option value="">Все</option>
			<?php if (isset($statuses)&&count($statuses)>0){?>
			<?php foreach ($statuses as $st){?>
			<option style="background:#<?=$st['color']?>;" value="<?=$st['id']?>"  <?=(isset($search['status']) && $search['status']==$st['id'])?'selected':''?>><?=$st['name']?></option>
			<?php }?>
			<?php }?>
		</select>
	</td>
	
	<td width="100px"><b>по офису</b></td>
	<td class="tdbrd">
	<select name="search[office_id]" class="iput"  style="width:100%;">
		<option value=""></option>
		<?php if (isset($offices) && count($offices)>0){?>
		<?php reset($offices); foreach ($offices as $office){?>
		<option value="<?=$office['office_id']?>" <?=(isset($search['office_id']) && $search['office_id'] == $office['office_id'])?'selected':'';?>><?=$office['city_name']?> &raquo; <?=$office['office_name']?></option>
		<?php }?>
		<?php }?>
	</select>
	</td>
</tr>
<tr>
	<td colspan="8" class="tdbrd">
		<button type="submit" class="btn btn-blue">Найти <img src="/media-templates/icons/magnifier.png"/></button>
	</td>
</tr>
</table>
</form>