<?php $this->block('index/crm/orders_filters');?>

<div class="clear"></div>
<?php if (isset($bills) && count($bills)>0){?>

<?php
	$uri = $_SERVER['REQUEST_URI'];
	$uri = preg_replace("|&?page=[0-9]+&?|", "", $uri);
	$uri = preg_replace("|\?$|", "", $uri);
	$has_params = (strpos($uri, "?") !== false);
	if ($has_params) {
		$uri .= "&";
	}
	else {
		$uri .= "?";
	}
?>
<?php if (isset($totalPages) && $totalPages>1) {?>
<div class="simple-paging" style="float:none;text-align:center;padding:7px 0px 2px 0px;">
	Страницы: <?=PagingViewHelper::paging($uri."page=:page:",$totalPages,$currentPage);?>
</div>
<div class="clear"></div>
<?php }?>

<?php if (isset($accountSearchById) && count($accountSearchById)>0){?>
<h1 class="h1-header top-10">Клиент <?=$accountSearchById['name']?></h1>
<style>
.padtd {}
.padtd td { padding:5px; text-align:center; }
.padtd td a { font-size:11px; }
</style>
<table class="details-list orders-grid padtd" cellpadding="5px" cellspacing="0px" style="width:100%;">
<thead>
<tr style="background-color:#F0FCD6;">
	<td style="font-weight:bold;text-align:center;">ID</td>
	<td style="font-weight:bold;text-align:center;">Код</td>
	<td style="font-weight:bold;text-align:center;">E-mail</td>
	<td style="font-weight:bold;text-align:center;">Имя</td>
	<td style="font-weight:bold;text-align:center;">Телефон</td>
	<td style="font-weight:bold;text-align:center;">Адрес</td>
	<td style="font-weight:bold;text-align:center;">Описание</td>
	<td style="font-weight:bold;text-align:center;">Скидка (Общая)</td>
	<td style="font-weight:bold;text-align:center;">Группа</td>
	<td style="font-weight:bold;text-align:center;">Баланс</td>
	<td style="font-weight:bold;text-align:center;">Менеджер</td>
	<td style="font-weight:bold;text-align:center;">Офис</td>
	<td style="font-weight:bold;text-align:center;">Подробнее</td>
	<td style="font-weight:bold;text-align:center;">Финоперации</td>
</tr>
</thead>
<tbody>
<tr>
	<td><?=$accountSearchById['id']?></td>
	<td><?=$accountSearchById['account_code']?></td>
	<td><?=$accountSearchById['email']?></td>
	<td><?=$accountSearchById['name']?></td>
	<td><?=$accountSearchById['phones']?></td>
	<td><?=$accountSearchById['address']?></td>
	<td><?=$accountSearchById['info']?></td>
	<td><?=$accountSearchById['discount']?>%</td>
	<td><?=(isset($accountSearchById['discountname'])?$accountSearchById['discountname']:'нет')?></td>
	<td><?=PriceHelper::number($accountSearchById['balance'])?></td>
	<td><?=(isset($accountSearchById['managerName'])?$accountSearchById['managerName']:'нет')?></td>
	<td><?=(isset($accountSearchById['Office'])?$accountSearchById['Office']:'нет')?></td>
	
	<td><a href="/staffcp/accounts/edit/?id=<?=$accountSearchById['id']?>">подробнее</a></td>
	<td><a href="/staffcp/accounts/operation/?id=<?=$accountSearchById['id']?>">финоперации</a></td>
</tr>
</tbody>
</table>
<?php }?>

<?php if(isset($search['number'])&&$search['number']){?>
<script type="text/javascript">
$(document).ready(function() {
	$.post('/staffcp/index/crm_list_orders/?ajax=true&not_view_filters=true&search[number]=<?=$search['number']?><?=(isset($_REQUEST['email'])?'&email='.$_REQUEST['email']:'')?><?=(isset($_REQUEST['sms'])?'&sms='.$_REQUEST['sms']:'')?>', null,
	function(data) {
		$("#aresorders").html(data);
	});
});
</script>
<div id="aresorders"></div>
<?php }?>

<script type="text/javascript">
function check_value_action(value){
	$('.setformparams').hide();
	if (value == 'changeStatus'){
		$('#changeStatus').show();
	}
	if (value == 'changeTimedelivery'){
		$('#changeTimedelivery').show();
	}
	if (value == 'changeGivetoclient'){
		$('#changeTimedelivery').show();
	}
}
</script>

<h1 class="h1-header top-10">Список позиций</h1>
<form action="" method="POST">
<table class="ss" width="100%">
<tr>
	<td class="tdbrd" style="padding-bottom:5px;font-weight:bold;text-align:center;">
	
	<?php 
	if (isset($__notice) && $__notice){
		echo('<b style="color:green;">');
		switch ($__notice){
			case 'email': echo('E-mail уведомления отправлены!'); break;
			case 'sms': echo('SMS уведомления отправлены!'); break;
		}
		echo('</b>&nbsp;&nbsp;&nbsp;&nbsp;');
	}
	?>
	
	Операции над выбранными позициями
	<select name="set_operation" class="iput" style="width:auto;" onchange="check_value_action(this.value);">
		<option value=""></option>
		<option value="changeStatus">сменить статус</option>
		<option value="setPayments" style="background:#c5ffb8;">провести оплаты</option>
		<option value="unsetPayments" style="background:#c5ffb8;">снять оплаты</option>
		<option value="isPayback" style="background:red;color:#fff;">возврат от покупателя</option>
		<option value="sendEmailNotices">отправить e-mail уведомление</option>
		<option value="sendSMSNotices">отправить sms уведомление</option>
		<option value="changeTimedelivery">сменить ожидаемый срок</option>
		<option value="changeGivetoclient">сменить дату выдачи заказа</option>
		<option value="deleteItems" style="color:#CC0000;">удалить</option>
		<?/*
		<option value="">экспорт в Excel</option>
		<option value="">заказ поставщику</option>
		<option value="">проверить позиции</option>
		*/?>
	</select>
	
	<span id="changeStatus" class="no-display setformparams">
		<b>статус</b>
		<?php if (isset($statuses)&&count($statuses)>0){?>
		<select name="set_operation_status" style="width:auto;" class="iput">
		<option value=""></option>
		<option value="0">Новый</option>
		<?php foreach ($statuses as $st){?>
		<option value="<?=$st['id']?>" style="background:#<?=$st['color']?>;" <?=(isset($element['ds_id']) && $element['ds_id']==$st['id'])?'selected':''?>><?=$st['name']?></option>
		<?php }?>
		</select>
		<?php }?>
	</span>
	<span id="changeTimedelivery" class="no-display setformparams">
		<b>ожидаемый срок</b>
		<input type="text" name="dtchangeTimedelivery" id="dtchangeTimedelivery" value="<?=date("d.m.Y")?>" class="iput" style="width:150px;"/>
		<input type="button" id="dtchangeTimedelivery_picker" value="&raquo;" class="btn">
		<script type="text/javascript">
		$(document).ready(function() {
			Calendar.setup({inputField: 'dtchangeTimedelivery',button: 'dtchangeTimedelivery_picker',date: '<?=date('d.m.Y')?>'});
		});
		</script>
	</span>
	
	<input type="submit" value="сохранить" class="btn btn-blue">
	</td>
</tr>
</table>

<div class="result-view-positions">
<div>

<table class="details-list orders-grid views-pos" cellpadding="0px" cellspacing="0px" width="100%">
<thead>
<tr style="background-color:#F0FCD6;">
	<td style="border-top:1px solid #DADADA;"></td>
	<td style="border-top:1px solid #DADADA;"></td>
	<td style="border-top:1px solid #DADADA;" align="center"><input type="submit" value="сохранить" class="btn btn-blue"></td>
	<td style="border-top:1px solid #DADADA;"></td>
	<td colspan="20" style="border-top:1px solid #DADADA;font-weight:bold;"></td>
</tr>
<tr>
	<td style="font-weight:bold;width:10px;text-align:center;"><input type="checkbox" onclick="setchk(this);" value="1"></td>
	<td style="font-weight:bold;width:10px;text-align:center;"><img src="/media-templates/icons/calendar.png" title="" /></td>
	<td style="font-weight:bold;width:;text-align:center;"><?=$translates['status']?></td>
	<td style="font-weight:bold;width:;text-align:center;">Дата</td>
	<td style="font-weight:bold;width:;text-align:center;"><?=$translates['admin.main.ordernumber']?></td>
	<td style="font-weight:bold;width:;text-align:center;">Клиент</td>
	<td style="font-weight:bold;width:125px;text-align:center;"><?=$translates['admin.details.art']?></td>
	<td style="font-weight:bold;width:;text-align:center;"><?=$translates['admin.index.brand']?></td>
	<td style="font-weight:bold;width:;text-align:center;"><?=$translates['admin.index.name']?></td>
	<td style="font-weight:bold;width:;text-align:center;"><img src="/media-templates/icons/page_white.png" title="" /></td>
	<td style="font-weight:bold;width:;text-align:center;"><?=$translates['admin.details.importer']?></td>
	<td style="font-weight:bold;width:;text-align:center;"><?=$translates['admin.details.boxlim']?></td>
	<td style="font-weight:bold;width:;text-align:center;">Закупка</td>
	<td style="font-weight:bold;width:;text-align:center;">Закупка<br>(сумма)</td>
	<td style="font-weight:bold;width:;text-align:center;">Продажа</td>
	<td style="font-weight:bold;width:;text-align:center;">Продажа<br>(сумма)</td>
	<td style="font-weight:bold;width:;text-align:center;"><?=$translates['admin.details.cost.oplacheno']?></td>
	<td style="font-weight:bold;width:;text-align:center;"><?=$translates['admin.details.cost.dolg']?></td>
	<td style="font-weight:bold;width:;text-align:center;">Ожид. срок</td>
	<td style="font-weight:bold;width:;text-align:center;">Выдача заказа</td>
	<td style="font-weight:bold;width:10px;text-align:center;" align="center"><img src="/media-templates/icons/comment.png" title="" /></td>
	<td style="font-weight:bold;width:10px;text-align:center;" align="center"><img src="/staffcp/media/images/pencil_16.png" title="<?=$translates['admin.main.edit']?>" /></td>
	<td style="font-weight:bold;width:10px;text-align:center;" align="center"><img src="/staffcp/media/images/trash_16.png" title="<?=$translates['admin.main.delete']?>" /></td>
	<td style="font-weight:bold;width:10px;text-align:center;" align="center"><img src="/staffcp/media/images/printer.png" title="" /></td>
</tr>
</thead>
<tbody>
<?php $sum=$sum_purchase=$i=$stopItem=$stopItemLast=$stopItemLastPrint=0;?>

<?php foreach ($bills as $number=>$billGroup){?>
<?php foreach ($billGroup as $element){?>
<?php $CCMESSAGES = BillsModel::getNewMessages($element['bill_number']);?>
<?php $i++;$stopItem++;$stopItemLast++;$stopItemLastPrint++;?>
<?php $ss = ($element['price']*$element['cc']);?>
<?php $ss_purchase = ($element['price_purchase']*$element['cc']);?>
<?php $sum_purchase += $ss_purchase;?>
<?php $rowspan = count($bills[$number]);?>

<?php $sum += $ss;?>
<?php $sum += ($i==1)?$element['bill_delivery_price']:0;?>

<tr style="background:#<?=($element['status']==0)?'':$element['ds_color']?>;">
	<?php /* $stopItemLastPrint *********************************** */?>
	<?php /*if ($stopItemLastPrint <= 1){?>
	<td rowspan="<?=$rowspan?>"></td>
	<?php } if($stopItemLastPrint==$rowspan) $stopItemLastPrint = 0;*/?>
	<?php /* $stopItemLastPrint *********************************** */?>
	
	<td align="center"><input class="setchk" type="checkbox" name="set_operation_item_ids[<?=$element['bill_id']?>][]" value="<?=$element['id']?>" id="set_operation_item_ids_<?=$element['id']?>"/></td>
	<td align="center"><a href="/staffcp/index/crm_history/?id=<?=$element['id']?>" class="form-action"><img src="/media-templates/icons/calendar.png" style="vertical-align:middle;"></a></td>
	<td style="<?=(($element['is_payback'])?'background:red;':'');?>" align="center">
	
		<?php if (isset($statuses)&&count($statuses)>0){?>
		<select name="items_save_statuses[<?=$element['id']?>]" style="padding:2px;width:95%;" class="iput">
		<?php if ($element['ds_id']){?>
		<option value="<?=$element['ds_id']?>" style="background:#<?=$element['ds_color']?>;" selected>- <?=$element['ds_name']?></option>
		<option value="0"></option>
		<?php }?>
		
		<option value="0">Новый</option>
		<?php foreach ($statuses as $st){?>
		<option value="<?=$st['id']?>" style="background:#<?=$st['color']?>;"><?=$st['name']?></option>
		<?php }?>
		</select>
		<?php }?>
		
		<?php if ($element['IS_ACCOUNT_ACCEPT']&&$element['ds_type']==2){?>
		<br/><img src="/staffcp/media/images/flag.gif"/><b><?=$translates['admin.accept']?></b>
		<?php }?>
		<?php if ($element['is_payback']){?><b style="color:#FFF; font-weight:bold; display:block;">Внимание! Отказ от товара</b><?php }?>
		
	</td>
	<td align="center" style="font-size:10px;">
		<?=date("d.m.Y H:i",$element['bill_dt'])?>
	</td>
	<td align="center" style="font-size:10px;">
		<a class="dotted" href="?search[number]=<?=$element['bill_number']?><?php if ($dd['bill_account_id']){?>&search[account_id]=<?=$dd['bill_account_id']?><?php }?>"><b>№-<?=$element['bill_number']?></b></a><br>
	</td>
	<td style="padding:10px;font-size:10px;" align="center">
		<a class="dotted" href="?search[account_id]=<?=$element['bill_account_id']?>"><?=$element['bill_f1']?></a>
	</td>
	<td align="center"><a class="iframe" href="/search/number/?simpleview=true&simple_account_id=<?=isset($element['bill_account_id'])?$element['bill_account_id']:0?>&simple_scsid=<?=$element['bill_scSID']?>&article=<?=$element['article']?>&searchbrand=<?=urlencode($element['brand'])?>"><b><?=$element['article']?></b></a></td>
	<td align="center"><b><?=$element['brand']?></b></td>
	<td align="center"><?=($element['descr_tecdoc'])?$element['descr_tecdoc']:$element['descr']?></td>
	<td style="text-align:center;">
		<div class="note-toggle">
			<span><img src="/media-templates/icons/<?=($element['status_descr']||$element['sold'])?'page_white_lightning':'page_white'?>.png" title="" /></span>
			<div>
			<p><b>Комментарий:</b> <?=($element['status_descr'])?$element['status_descr']:'нет'?></p>
			<p><b>Заметка:</b> <?=($element['sold'])?$element['sold']:'нет'?></p>
			</div>
		</div>
	</td>
	<td align="center">
		<?php if ($element['IS_ACCOUNT']){?>
			<?php $a_imp = AccountsModel::getById($element['IS_ACCOUNT']);?>
			<a style="color:#000;" href="/staffcp/accounts/edit/?id=<?=$element['IS_ACCOUNT']?>"><b><img src="/staffcp/media/images/flag.gif"/> <?=$a_imp['name']?></b></a>
		<?php }else{?>
			<b><?=$element['imp_name']?></b>
		<?php }?>
	</td>
	<td align="center"><?=$element['cc']?></td>
	
	<td align="center"><?=PriceHelper::number($element['price_purchase'])?></td>
	<td align="center"><?=PriceHelper::number($ss_purchase)?></td>
	
	<td align="center"><?=PriceHelper::number($element['price'])?></td>
	<td align="center"><?=PriceHelper::number($ss)?></td>
	
	<td align="center">
	<?php if ($element['bill_account_id']){?>
		<?=($element['balance_minus'])?PriceHelper::number($ss):''?>
	<?php }else{?>-<?php }?>
	</td>
	<td align="center">
	<?php if ($element['bill_account_id']){?>
		<?=($element['balance_minus'])?(0):PriceHelper::number($ss)?>
	<?php }else{?>-<?php }?>
	</td>
	<td align="center">
		<?php if ($element['time_delivery_wait_dt']) {?>
		<b style="font-size:10px;">
			<?=date("d.m.Y",$element['time_delivery_wait_dt'])?><br />
			<?php $daysOff = AgoViewHelper::before(date("Y-m-d",$element['time_delivery_wait_dt']));?>
			<?php if ($daysOff>0) {?>
			ост.:&nbsp;<?=$daysOff?>&nbsp;дн.
			<?php }elseif ($daysOff==0) {?>
			<span style="color:green;font-weight:bold;font-size:10px;">сегодня</span>
			<?php }?>
		</b>
		<?php }?>
		<?php if ($element['time_delivery_descr']){?><p style="padding:1px 1px 1px 1px;margin:0px;font-size:10px;color:blue;line-height:10px;font-weight:bold;">срок: <?=$element['time_delivery_descr']?> дн.</p><?php }?>
	</td>
	<td style="padding:10px;font-size:10px;font-weight:bold;" align="center">
		<?php if ($element['time_give_order']){?>
			<?=date("d.m.Y",$element['time_give_order'])?>
		<?php }else{?>
			<a href="/staffcp/index/order/?edit_order=<?=$element['bill_id']?>&item=<?=$element['id']?>"><img src="/media-templates/icons/date_add.png"/></a>
		<?php }?>
	</td>
	<td align="center"><a style="font-size:11px; font-weight:bold; color:red;" href="/staffcp/index/order/?edit_order=<?=$element['bill_id']?>&unset_new=true#messages"><img title="" alt="" src="/media-templates/icons/comment.png" style="vertical-align: top;"><?php if ($CCMESSAGES){?>&nbsp;(<?=$CCMESSAGES?>)<?php }?></a></td>
	<td align="center"><a href="/staffcp/index/order/?edit_order=<?=$element['bill_id']?>&item=<?=$element['id']?>"><img border="0" src="/staffcp/media/images/pencil_16.png" title="<?=$translates['admin.main.edit']?>"></a></td>
	<td align="center"><?php if (!$isManager){?><a onclick="return confirm('<?=$translates['admin.main.confirm']?>');" href="?del=<?=$element['id']?>"><img src="/staffcp/media/images/trash_16.png" title="<?=$translates['admin.main.delete']?>" /></a><?php }else{?>x<?php }?></td>
	<td align="center"><a href="/staffcp/index/printbill/?id=<?=$element['bill_number']?>" style="font-size:10px;font-weight:bold;"><img src="/staffcp/media/images/printer.png"/></a></td>
</tr>

<?php } // foreach ?>
<?php } // for ?>

<tr style="background-color:#F0FCD6;">
	<td></td>
	<td></td>
	<td align="center"><input type="submit" value="сохранить" class="btn btn-blue"></td>
	<td></td>
	<td align="center"></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td align="center" style="padding:10px 0px;width:100px;"><b><?=PriceHelper::number($sum_purchase)?></b></td>
	<td></td>
	<td align="center" style="padding:10px 0px;width:100px;"><b><?=PriceHelper::number($sum)?></b></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
</tr>
</tbody>
</table>
</form>

<div class="clear"></div>
<?php if (isset($totalPages) && $totalPages>1) {?>
<div class="simple-paging" style="float:none;text-align:center;padding:7px 0px 2px 0px;">
	Страницы: <?=PagingViewHelper::paging($uri."page=:page:",$totalPages,$currentPage);?>
</div>
<div class="clear"></div>
<?php }?>

</div>
</div>

<?php } else {?>
<p><b><?=$translates['noorders']?></b></p>
<?php }?>

<center>
<a style="margin:5px auto;" href="/staffcp/importers/pchart/" class="btn btn-blue">Сформировать графики эффективности поставщиков <img src="/media-templates/img/chart_pie.png"></a>
</center>