<h1 class="h1-header">
<span><?=$title;?></span>
<a href="<?=$listUrl;?>" class="btn btn-blue"><?=$listTitle;?></a>
</h1>
<form autocomplete="off" action="/staffcp/<?=$this->dataModel->getModelName();?>/save/" method="POST" enctype="multipart/form-data">
<div id="tabs" class="tabs">
    <ul>
    	<?php foreach ($tabs as $tabId=>$tabName){?>
        <li><a href="#tab-<?=$tabId;?>"><span><?=$tabName;?></span></a></li>
        <?php }?>
        <li><a href="#tab-cars"><span>Автомобили клиента</span></a></li>
    </ul>
    <?php foreach ($tabs as $tabId=>$tabName){?>
    
    <div id="tab-<?=$tabId;?>">
	<table class="form">
	<?php foreach ($tabFields[$tabName] as $fieldName=>$field){?>
		<?php if ($field->hasLayout){?>
		<tr>
			<td class="label"><?=$this->dataModel->getFieldLabel($fieldName);?></td>
			<td><?=$field->getFormValue();?></td>
		</tr>
		<?php }?>
	<?php }?>
	<?php if ($tabId == 5) {?>
	<tr>
		<td class="label"></td>
		<td>
		<?php /* ****************************** */?>    
	    <p style="padding:4px 14px;"><b>
	    	Установить по умолчанию для всех: 
	    	<?php if (isset($listMargins) && count($listMargins)>0){?>
		<?php foreach ($listMargins as $margin){?>
			&nbsp;&nbsp;<a href="#" onclick="$('.marginsids').val('<?=$margin['id']?>');"><?=$margin['name']?> (<?=$margin['extra']?>%)</a>
		<?php }?>
		<?php }?>
	    </b></p>
	    
	   	<table class="cms-list">
	   	<thead>
   		<tr>
   			<th style="width:50px;">id</th>
   			<th style="width:200px;">Постащик</th>
   			<th>Группа наценок</th>
	   		<th>Открыть доступ (работает, если активирована - функ. ограничения доступа)</th>
   		</tr>
	   	</thead>
	   	<tbody>
	   	<?php if (isset($importers) && count($importers)>0){?>
	   	<?php foreach ($importers as $dd){?>
   		<tr>
   			<td><b><?=$dd['id']?></b></td>
   			<td><b><?=$dd['name']?></b></td>
   			<td>
   				<select name="importers[<?=$dd['id']?>]" class="marginsids">
   				<option value="0"></option>
   				<?php if (isset($listMargins) && count($listMargins)>0){?>
   				<?php foreach ($listMargins as $margin){?>
   					<option value="<?=$margin['id']?>" <?=(isset($save_margins[$dd['id']]) && $save_margins[$dd['id']] == $margin['id'])?'selected':'';?>><?=$margin['name']?> (<?=$margin['extra']?>%)</option>
   				<?php }?>
   				<?php }?>
   				</select>
   			</td>
	   		<td><input type="checkbox" name="iaccess[]" value="<?=$dd['id']?>" <?=(isset($save_iaccess)&&in_array($dd['id'], $save_iaccess))?'checked':'';?>/></td>
   		</tr>
	   	<?php }?>
	   	<?php }?>
	   	</tbody>
	   	</table>
	    <?php /* ****************************** */?>
		</td>
	</tr>
	<?php }?>
	</table>
	</div>
    <?php }?>
	
	<div id="tab-cars">
		<?php $listcars = AccountsModel::getByIdCarsAll($indexValue);?>
		<?php if (isset($listcars) && count($listcars)>0){?>
			<?php foreach ($listcars as $car){?>
			<div style="display:block; margin:5px;">
				<b><?=$car['car_info']?></b> :: <b><?=$car['car_vin']?></b> :: <a href="/staffcp/accounts_cars/edit/?id=<?=$car['id']?>"><?=$car['car_name']?> <?=$car['car_year']?></a>
			</div>
			<?php }?>
		<?php }else{?>
		Автомобилей нет
		<?php }?>
	</div>     
</div>
<input type="hidden" name="form[<?=$indexField;?>]" value="<?=$indexValue;?>" />
<input type="submit" value="<?=$submit?>" id="submit_action" class="btn btn-blue">
</form>