<h1 class="uppercase"><?=((isset($_REQUEST['CONTACT']))?$translates['front.request.quest1'].' '.$_REQUEST['CONTACT'].'. '.$translates['front.request.quest2'].'':$translates['front.request.form'])?></h1>

<form action="<?=HTTP_ROOT?>/contacts/send/" method="post" id="form_reg" onsubmit="return chkreg();">
	<table width="100%" class="contact-form">
		<tr>
			<th><?=$translates['front.cart.form.name']?>*</th>
			<td>
				<input type="text" name="form[name]" id="form_name" class="form_elements" value="<?=(isset($error_data)&&!empty($error_data['name']))?$error_data['name']:''?>"/>
				<span class="msg-error" id="form_name_err"></span>
			</td>
		</tr>
		<tr>
			<th><?=$translates['front.cart.form.phone']?>*</th>
			<td>
				<input type="text" name="form[phone]" id="form_phone" class="form_elements" value="<?=(isset($error_data)&&!empty($error_data['phone']))?$error_data['phone']:''?> <?=(isset($error_data)&&!empty($error_data['phones']))?$error_data['phones']:''?>"/>
				<span class="msg-error" id="form_phone_err"></span>
			</td>
		</tr>
		<tr>
			<th><?=$translates['front.account.email']?></th>
			<td>
				<input type="text" name="form[email]" id="form_email" class="form_elements" value="<?=(isset($error_data)&&!empty($error_data['email']))?$error_data['email']:''?>"/>
				<span class="msg-error" id="form_email_err"></span>
			</td>
		</tr>
		<tr>
			<th><?=$translates['front.account.subject']?>*</th>
			<td>
				<input type="text" name="form[subject]" id="form_subject" class="form_elements" value="<?=(isset($error_data)&&!empty($error_data['subject']))?$error_data['subject']:''?>"/>
				<span class="msg-error" id="form_subject_err"></span>
			</td>
		</tr>
		<tr>
			<th><?=$translates['front.cart.form.message']?>*</th>
			<td>
				<textarea name="form[message]" id="form_message" class="form_elements" rows="" cols=""><?=(isset($error_data)&&!empty($error_data['message']))?$error_data['message']:((isset($_REQUEST['CONTACT']))?$translates['front.request.quest'].' '.$_REQUEST['CONTACT']:'')?></textarea>
				<span class="msg-error" id="form_message_err"></span>
			</td>
		</tr>
		<tr>
			<th></th>
			<td>
				<p><img src="/extensions/captcha/index.php" /></p>
				<input type="text" name="form[code]" id="form_code" value="" class="form_elements"/>
				<p class="msg-error" id="form_code_err"></p>
			</td>
		</tr>
		<tr>
			<th></th>
			<td><input type="submit" value="<?=$translates['front.send']?>" class="custom-button"/></td>
		</tr>
	</table>
</form>

<script type="text/javascript">
function chkreg() {
	var err = "";
	$('.form_elements_err').removeClass('form_elements_err').addClass('form_elements');
	$('.msg-error').html('');
	var msg1 = $('#form_name').val();
	if (msg1=="") {
		err += 'err';
		$('#form_name_err').html('<?=$translates['front.fields.err']?> - <?=$translates['front.cart.form.name']?>');
		$('#form_name').removeClass('form_elements').addClass('form_elements_err');
	}
	var msg1 = $('#form_phone').val();
	if (msg1=="") {
		err += 'err';
		$('#form_phone_err').html('<?=$translates['front.fields.err']?> - <?=$translates['front.cart.form.phone']?>');
		$('#form_phone').removeClass('form_elements').addClass('form_elements_err');
	}
	/*var email = $('#form_email').val();
	if (email=="" || !/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,4})+$/.test(email)) {
		err += 'err';
		$('#form_email_err').html('<?=$translates['front.fields.err.email']?>');
		$('#form_email').removeClass('form_elements').addClass('form_elements_err');
	}*/
	var msg1 = $('#form_subject').val();
	if (msg1=="") {
		err += 'err';
		$('#form_subject_err').html('<?=$translates['front.fields.err']?> - <?=$translates['front.account.subject']?>');
		$('#form_subject').removeClass('form_elements').addClass('form_elements_err');
	}
	var msg1 = $('#form_message').val();
	if (msg1=="") {
		err += 'err';
		$('#form_message_err').html('<?=$translates['front.fields.err']?> - <?=$translates['front.cart.form.message']?>');
		$('#form_message').removeClass('form_elements').addClass('form_elements_err');
	}
	var msg2 = $('#form_code').val();
	if (msg2=="") {
		err += 'err';
		$('#form_code_err').html('<?=$translates['front.fields.err2']?>');
		$('#form_code').removeClass('form_elements').addClass('form_elements_err');
	}
	if (err == "") {
		return true;
	}
	else {
		return false;
	}
}
</script>

<?php if ($send==1){?>
<script>
$(document).ready(function() {
	alert('<?=$translates['front.contact.accept']?>');
});
</script>
<?php } elseif ($send==2){?>
<script>
$(document).ready(function() {
	alert('<?=$translates['front.cart.captcha.err']?>');
});
</script>
<?php }?>