<?php $informer = Informer::money_KZ();?>
<?php if (isset($informer) && count($informer)>0){?>
<table>
<?php foreach ($informer as $cur=>$val){?>
<tr>
	<td><b>Курс <?=$cur?></b></td>
	<td>
		<input type="hidden" name="<?=$cur?>" id="KZ_ex_<?=$cur?>" value="<?=$val?>">
		<?=$val?>
	</td>
</tr>
<?php }?>
<tr>
	<td><b>Курс EUR/USD</b></td>
	<td>
		<input type="hidden" name="EUR_USD" id="KZ_ex_EUR_USD" value="<?=($informer['EUR']/$informer['USD'])?>">
		<?=($informer['EUR']/$informer['USD'])?>
	</td>
</tr>
</table>
<?php }?>