<?php if($ga_u && $ga_p && $ga_id){?>

	<div id="GA-Result"><img src="/staffcp/media/images/30-0.gif" alt="" title="" style="vertical-align:middle;"/> <b>загрузка данных Google Analytics</b></div>
	<script type="text/javascript">
	jQuery(document).ready(function(){
		$.post('/staffcp/index/ajaxGA/', null,
		function(data) {
			$("#GA-Result").html(data);
		});
	});
	</script>

<?php }else{?>

	<h1 class="h-title">Настройка статистики</h1>
	<div>
		<p style="font-size:12px;">Не введены данные для получения статистики в разделе настройки вкладка Google Analytics</p>
		<p><a href="/staffcp/settings/#tab-1" class="btn btn-blue">Настроить</a></p>
	</div>
	<br>
	<h1 style="font-size:12px;color:red;">Где брать индификатор профиля?</h1>
	<a href="/staffcp/media/images/GA.png" target="_blank"><img alt="" src="/staffcp/media/images/GA.png" width="200px" style="border:solid 4px #dadada;"></a>
	
	
<?php }?>