<table width="100%">
<tr>
	<td valign="top">

<div class="fast-orders-shopping-stop">
	<ul class="systems-orders">
		<li class="title"><b>Список заказов</b></li>
		<li class="clear"></li>
		<li><b><a class="btn" href="/staffcp/index/crm_list_orders/">Все заказы <span class="cc-alarm"><?=$fullOrderCCNew?></span> (<?=$fullOrderCCOther?>)</a></b></li>
		
		<li class="clear"></li>
		<li class="title"><b>Позиции заказов</b></li>
		<li class="clear"></li>
		<?php if (isset($newBills['cc']) && $newBills['cc']){?>
		<li><b><a class="btn btn-green" href="/staffcp/index/crm/?search[only_new]=true#tab-1">Новые позиции заказов (<?=$newBills['cc']?>)</a></b></li>
		<?php }?>
		<li><b><a class="btn" href="/staffcp/index/crm/#tab-1">Активные позиции заказов <span class="cc-alarm"><?=$ccBills['cc']?></span></a></b></li>
		<li><b><a class="btn" href="/staffcp/index/crm/?search[archive]=true#tab-1">Выполненные позиции заказов (<?=$doneBills['cc']?>)</a></b></li>
	</ul>
	<div class="clear"></div>
</div>
<div class="clear"><br/></div>

<div class="fast-orders-shopping-stop">
	<ul class="systems-orders f-left">
		<li class="title"><b>Добавить новый заказ</b></li>
		<li class="clear"></li>
		<?php if ($shopping_account){?>
		<?php $data_account = AccountsModel::getById($shopping_account);?>
		<li class="buttons">
			<input type="button" name="" value="Продолжить заказ на <?=$data_account['name']?> <?=$data_account['phones']?>" onclick="location='/staffcp/index/shopping/';" class="btn btn-blue">
		</li>
		<li class="buttons">
			<input type="button" name="" value="Снять заказ" onclick="location='/staffcp/index/shopping/?action=unsetperson';" class="btn btn-blue">
		</li>
		<?php }else{?>
		<li class="buttons">
			<input type="button" name="" value="Новый клиент" onclick="location='/staffcp/accounts/add/';" class="btn btn-blue">
		</li>
		<li class="buttons">
			<input type="button" name="" value="Найти клиента" onclick="location='/staffcp/accounts/';" class="btn btn-blue">
		</li>
		<?php }?>
	</ul>
	<ul class="systems-orders f-left">
		<li class="title"><b>Быстрый заказ</b></li>
		<li class="clear"></li>
		<li class="buttons">
			<a href="/staffcp/index/shopping/?client=false" class="btn">Оформить заказ без клиента</a>
		</li>
		<li class="buttons">
			<a href="/staffcp/index/fastorder/" class="btn btn-green form-action">Оформить быстрый заказ</a>
		</li>
	</ul>
	<div class="clear"></div>
	<?php if (isset($tempOrders) && count($tempOrders)>0){?>
	<ul class="systems-orders">
		<li class="title"><b>Список приостановленных заказов</b></li>
		<li class="clear"></li>
		<?php foreach ($tempOrders as $tempOr){?>
		<li class="clear"><a href="/staffcp/index/shopping/?action=restore&restore_id=<?=$tempOr['id']?>">Продолжить оформление заказа за <?=date("d.m.Y H:i",$tempOr['save_dt'])?></a> / <?=$tempOr['notice']?> <?=$tempOr['name']?> <?=$tempOr['phone']?></li>
		<?php }?>
	</ul>
	<?php }?>
	<div class="clear"></div>
</div>
<div class="clear"><br></div>

<?php if (!$isManager){?>
<div class="fast-orders-shopping-stop">
<table>
<tr>
	<td valign="top">
	
		<form action="/staffcp/index/set_currency/" method="POST" id="set-currency">
		<table width="100%">
		<tr>
			<td colspan="5">
				<b class="h-title">Обновить курсы валют на <?=date("d.m.Y")?></b> 
				&nbsp;::&nbsp;
				<a class="h-title" href="#" onclick="chk_status_of_bank('nbrb');return false;">НБРБ</a>
				&nbsp;::&nbsp;
				<a class="h-title" href="#" onclick="chk_status_of_bank('cbrf');return false;">ЦБРФ</a>
				&nbsp;::&nbsp;
				<a class="h-title" href="#" onclick="chk_status_of_bank('nbu');return false;">ЦБУ</a>
				&nbsp;::&nbsp;
				<a class="h-title" href="#" onclick="chk_status_of_bank('kz');return false;">ЦБРК</a>
			</td>
		</tr>
		<tr>
			<td><b>Курс доллара</b></td>
			<td><input type="text" name="currency" value="<?=$currency?>" id="usd_1" class="iput"></td>
			
			<td><b>Курс рубля</b></td>
			<td><input type="text" name="currency_rur" value="<?=$currency_rur?>" id="rur_1" class="iput"></td>
		</tr>
		<tr>
			<td><b>Курс евро</b></td>
			<td><input type="text" name="currency_eur" value="<?=$currency_eur?>" id="eur_1" class="iput"></td>
			<td><b>Курс евро/доллара</b></td>
			<td><input type="text" name="currency_usd_eur" value="<?=$currency_usd_eur?>" id="eur_usd_1" class="iput"></td>
		</tr>
		<tr>
			<td></td>
			<td><input type="button" type="submit" onclick="$('#set-currency').submit();" value="Сохранить" class="btn btn-blue"></td>
		</tr>
		</table>
		</form>
		<script type="text/javascript">
		function get_from_nbrb_1(){
			$('#usd_1').val($('#ex_USD').val());
			$('#eur_1').val($('#ex_EUR').val());
			$('#rur_1').val($('#ex_RUB').val());
			$('#eur_usd_1').val($('#ex_EUR_USD').val());
		}
		function get_from_cbrb_1(){
			$('#usd_1').val($('#RUSSIAN_ex_USD').val());
			$('#eur_1').val($('#RUSSIAN_ex_EUR').val());
			$('#rur_1').val(0);
			$('#eur_usd_1').val($('#RUSSIAN_ex_EUR_USD').val());
		}
		function get_from_nbu_1(){
			$('#usd_1').val($('#UKR_ex_USD').val());
			$('#eur_1').val($('#UKR_ex_EUR').val());
			$('#rur_1').val($('#UKR_ex_RUB').val());
			$('#eur_usd_1').val($('#UKR_ex_EUR_USD').val());
		}
		function get_from_kz_1(){
			$('#usd_1').val($('#KZ_ex_USD').val());
			$('#eur_1').val($('#KZ_ex_EUR').val());
			$('#rur_1').val($('#KZ_ex_RUB').val());
			$('#eur_usd_1').val($('#KZ_ex_EUR_USD').val());
		}
		</script>
			
	</td>
	<td valign="top">
		
		<script type="text/javascript">
		function chk_status_of_bank(id){
			$("#result_bank_of_"+id).html('Загрузка данных, пожалуйста, подождите...');
			$.post('/staffcp/index/bank_'+id+'/', null,
			function(data) {
				$("#result_bank_of_all").html(data);
				if (id == 'nbrb'){
					get_from_nbrb_1();
				}
				if (id == 'cbrf'){
					get_from_cbrb_1();
				}
				if (id == 'nbu'){
					get_from_nbu_1();
				}
				if (id == 'kz'){
					get_from_kz_1();
				}
			});
		}
		</script>
		<table cellpadding="2px">
			<tr><td id="result_bank_of_all"></td></tr>
		</table>
		
	</td>
</tr>
</table>
</div>

<div class="clear"><br></div>
<div class="fast-orders-shopping-stop">
<b class="h-title">Позиции ожидающие подтверждение заказа</b>
<table class="xsmall" width="100%" cellspacing="0px" cellpadding="0px">
<thead>
	<th>Клиент</th>
	<th>Дата добавления</th>
	<th>Артикул</th>
	<th>Бренд</th>
	<th>Описание</th>
	<th>Кол-во</th>
	<th>Цена</th>
	<th>Поставщик</th>
	<th>Удалить</th>
	<th>Прошло времени</th>
</thead>
<tbody>
<?php if (isset($unconfirmed_cart_items) && count($unconfirmed_cart_items)>0){?>
<?php foreach ($unconfirmed_cart_items as $dd){?>
<tr>
	<td style="font-size:11px;">
	<?php if($dd['account_name']){?>
		<a style="font-size:11px;" href="/staffcp/accounts/edit/?id=<?=$dd['account_id']?>"><?=$dd['account_name']?></a>
	<?php }else{?>
		Незарегистрированный
	<?php }?>
	</td>
	<td><?=date("d.m.Y-H:i",$dd['createDT'])?></td>
	<td><a class="iframe" href="/search/number/?simpleview=true&simple_account_id=<?=isset($dd['account_id'])?$dd['account_id']:0?>&simple_scsid=<?=$dd['scSID']?>&article=<?=$dd['article']?>&searchbrand=<?=urlencode($dd['brand'])?>"><?=$dd['article']?></a></td>
	<td><?=$dd['brand']?></td>
	<td><?=$dd['descr']?></td>
	<td><?=$dd['cc']?></td>
	<td><?=PriceHelper::number($dd['price'])?></td>
	<td><?php if($dd['imp_name']){?><?=$dd['imp_name']?> (<?=$dd['imp_code']?>)<?php }?></td>
	<td><a href="?unconfirmed_id_delete=<?=$dd['id']?>" style="display:inline-block;color:#999;font-size:11px;">Удалить</a></td>
	<td><?=AgoViewHelper::since($dd['createDT'])?></td>
</tr>
<?php }?>
<?php if($unconfItemsPages_num>1){?>
<tr>
	<td colspan="10" class="paging">
		Страницы: <?=PagingViewHelper::paging("?page=:page:",$unconfItemsPages_num,$unconfItemsPage)?>
	</td>
</tr>
<?php }?>
<tr>
	<td colspan="10" style="background: none repeat scroll 0 0 #f0f0f0;">
		<a href="?unconfirmed_all_delete=true">Очистить позиции</a>
	</td>
</tr>
<?php }else{?>
<tr>
	<td colspan="10">
		нет позиций
	</td>
</tr>
<?php }?>
</tbody>
</table>
</div>

<div class="clear"><br></div>
<div class="fast-orders-shopping-stop">
<b class="h-title">Последние <?=$limitLog?> действий в зоне администрирования</b>

<table class="xsmall" width="100%" cellspacing="0px" cellpadding="0px">
<thead>
	<th>Дата</th>
	<th>Пользователь</th>
	<th>Действие</th>
	<th>Адрес операции</th>
</thead>
<tbody>
<?php if (isset($logsList) && count($logsList)>0){?>
<?php foreach ($logsList as $dd){?>
<tr>
	<td><?=date("d.m.Y-H:i:s",$dd['dt'])?></td>
	<td><?=$dd['user']?></td>
	<td><?=$dd['descr']?></td>
	<td><a href="<?=$dd['url']?>" style="font-size: 10px;"><?=substr($dd['url'],0,70)?>...</a></td>
</tr>
<?php }?>
<tr>
	<td colspan="4" style="background: none repeat scroll 0 0 #f0f0f0;"><a href="?deletelogs" style="display:inline-block;color:#999;font-size:11px;">Удалить все логи действий</a></td>
</tr>
<?php }else{?>
<tr>
	<td colspan="4">нет действий</td>
</tr>
<?php }?>
</tbody>
</table>
</div>

<?php }?>

	</td>
	<td valign="top" class="fixed-data-info">
		
		<div class="office-data">
			<table>
			<?php if ($office['user_id']){?>
			<tr>
				<th>Менеджер</th>
				<td><sup><?=$office['user_id']?></sup> <?=$office['user_name']?></td>
			</tr>
			<?php }?>
			<?php if ($office['office_id']){?>
			<tr>
				<th>Офис</th>
				<td><sup><?=$office['office_id']?></sup> <?=$office['office_name']?></td>
			</tr>
			<?php }?>
			<?php if ($office['office_info']){?>
			<tr>
				<th></th>
				<td><?=$office['office_info']?></td>
			</tr>
			<?php }?>
			<?php if ($office['city_name']){?>
			<tr>
				<th>Город</th>
				<td><?=$office['city_name']?></td>
			</tr>
			<?php }?>
			</table>
		</div>
		
		
		<?php if (
		(isset($check_vins) && count($check_vins)>0) ||
		(isset($check_testimonials) && count($check_testimonials)>0) ||
		(isset($check_faqs) && count($check_faqs)>0)
		) {?>
		<div class="full-block-testim">
		
			<?php if (isset($check_vins) && count($check_vins)>0){?>
				<h1><a class="ap-tname" href="#" onclick="$('#it1').toggle();return false;">Запрос по Vin <span class="cc-alarm" style="float:none;"><?=count($check_vins)?></span></a> <a href="/staffcp/vin/">все</a></h1>
				<div style="display:none;" id="it1">
				<?php foreach ($check_vins as $vin){?>
				<div class="one-ittem-chk">
					<p class="date-testim">ID:<?=$vin['id']?> | <?=date("d.m.Y",$vin['dt'])?></p>
					<?php if ($vin['vin']) {?><p><b>Vin:</b> <?=$vin['vin']?></p><?php }?>
					<p><b>Запрос:</b> <?=strip_tags($vin['message'])?></p>
					<a href="/staffcp/vin/edit/?id=<?=$vin['id']?>">ответить</a>
				</div>
				<?php }?>
				</div>
			<?php }?>
			
			<?php if (isset($check_testimonials) && count($check_testimonials)>0){?>
				<h1><a class="ap-tname" href="#" onclick="$('#it2').toggle();return false;">Отзывы на проверку <span class="cc-alarm" style="float:none;"><?=count($check_testimonials)?></span></a> <a href="/staffcp/testimonials/">все</a></h1>
				<div style="display:none;" id="it2">
				<?php foreach ($check_testimonials as $chtestim){?>
				<div class="one-ittem-chk">
					<p class="date-testim">ID:<?=$chtestim['id']?> | <?=$chtestim['name']?> / <?=date("d.m.Y",$chtestim['dt'])?> / <b>(<?=$chtestim['raiting']?>)</b></p>
					<p><?=$chtestim['message']?></p>
					<a href="/staffcp/testimonials/edit/?id=<?=$chtestim['id']?>">проверить</a>
				</div>
				<?php }?>
				</div>
			<?php }?>
			
			<?php if (isset($check_faqs) && count($check_faqs)>0){?>
				<h1><a class="ap-tname" href="#" onclick="$('#it3').toggle();return false;">Вопрос-ответ <span class="cc-alarm" style="float:none;"><?=count($check_faqs)?></span></a> <a href="/staffcp/faq/">все</a></h1>
				<div style="display:none;" id="it3">
				<?php foreach ($check_faqs as $fid){?>
				<div class="one-ittem-chk">
					<p class="date-testim">ID:<?=$fid['id']?> | <?=$fid['question']?> / <?=date("d.m.Y",$fid['dt'])?></p>
					<a href="/staffcp/faq/edit/?id=<?=$fid['id']?>">проверить</a>
				</div>
				<?php }?>
				</div>
			<?php }?>
			
		</div>
		<?php }?>
		
		<?php if (!$isManager){?>
		<style>
		.staticticsuls { padding:0px; margin:0px 0px 0px 0px; list-style:none; }
		.staticticsuls li { padding:2px; }
		.staticticsuls a { color:#156299 !important; }
		</style>
		<div class="full-block-testim">
            <h1>Финансовая статистика</h1>
            <div class="one-ittem-chk">
            <ul class="staticticsuls">
            	<li>
            		Доход за 
            		<select onchange="location='/staffcp/?stat_month='+this.value;">
            		<?php for ($i=1;$i<=12;$i++){?>
            			<?php $i = (strlen($i)==1)?'0'.$i:$i;?>
            			<option value="<?=$i?>" <?=($stat_month == $i)?'selected':'';?>><?=$i?>.<?=date("Y");?></option>
            		<?php }?>
            		</select> 
            		: <span class="cc-alarm"><?=PreviewHelper::numberPreview($total_this_month)?></span>
            	</li>
            	<li>Доход за <?=date("Y")?>: <span class="cc-alarm"><?=PreviewHelper::numberPreview($total_this_year)?></span></li>
            	<li style="background:#f1f1f1;">Общий доход за весь период: <?=PreviewHelper::numberPreview($total_sum-$total_sum_purchase)?></li>
                <li>Общая сумма закупки: <?=PreviewHelper::numberPreview($total_sum_purchase)?></li>
                <li style="background:#f1f1f1;">Общая сумма продаж: <?=PreviewHelper::numberPreview($total_sum)?></li>
            </ul>
            </div>
        </div>
        
		<div class="full-block-testim">
            <h1>Статистика сайта</h1>
            <div class="one-ittem-chk">
            <ul class="staticticsuls">
                <li style="background:#f1f1f1;">Новых заказов за сегодня <?=date("d.m.Y")?>: <a href="/staffcp/index/crm/?search[only_new]=true"><span <?=($cc_ORDERS)?'class="cc-alarm"':'';?>><?=PreviewHelper::numberPreview($cc_ORDERS)?></span></a></li>
                <li>Зарегистрировано пользователей за <?=date('F Y')?>: <a href="/staffcp/accounts/"><?=PreviewHelper::numberPreview($cc_accounts_this_month)?></a></li>
                <li style="background:#f1f1f1;">Зарегистрировано пользователей: <a href="/staffcp/accounts/"><?=PreviewHelper::numberPreview($cc_accounts)?></a></li>
                <li>Кол-во поставщиков: <a href="/staffcp/importers/"><?=PreviewHelper::numberPreview($cc_importers)?></a></li>
                <li style="background:#f1f1f1;">База цен на сайте: <a href="/staffcp/details/"><?=PreviewHelper::numberPreview($cc_db_prices)?></a></li>
                <li>Активировано веб-проценок: <a href="/staffcp/wbs/"><?=PreviewHelper::numberPreview($cc_wbs)?></a></li>
                <li style="background:#f1f1f1;">База товаров магазина: <a href="/staffcp/cat/"><?=PreviewHelper::numberPreview($cc_products)?></a></li>
                <li>Кол-во новостей: <a href="/staffcp/news/"><?=PreviewHelper::numberPreview($cc_news)?></a></li>
                <li style="background:#f1f1f1;">Кол-во статей: <a href="/staffcp/articles/"><?=PreviewHelper::numberPreview($cc_articles)?></a></li>
            </ul>
            </div>
        </div>
        <?php }?>
		
	</td>
</tr>
</table>