<link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
<style>
body {
    background: url('https://images.unsplash.com/photo-1431223768934-5f53d42100b2?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&s=9c9cd300a7988c01e42a1b9f2d098faf') no-repeat fixed center center;
    background-size: cover;
    font-family: Montserrat;
}

.logo {
    color:#fff;
    font-family: Montserrat;
	text-align:Center;
	font-size:2.3em;
    margin: 30px auto;
}

.login-block {
    width: 320px;
    padding: 20px;
    background: #fff;
    border-radius: 5px;
    border-top: 5px solid #ff656c;
    margin: 0 auto;
	margin-top: 15vh;
}

.login-block h1 {
    text-align: center;
    color: #000;
    font-size: 18px;
    text-transform: uppercase;
    margin-top: 0;
    margin-bottom: 20px;
}

.login-block input {
    width: 100%;
    height: 42px;
    box-sizing: border-box;
    border-radius: 5px;
    border: 1px solid #ccc;
    margin-bottom: 20px;
    font-size: 14px;
    font-family: Montserrat;
    padding: 0 20px 0 50px;
    outline: none;
}

.login-block input#username {
    background: #fff url('http://i.imgur.com/u0XmBmv.png') 20px top no-repeat;
    background-size: 16px 80px;
}

.login-block input#username:focus {
    background: #fff url('http://i.imgur.com/u0XmBmv.png') 20px bottom no-repeat;
    background-size: 16px 80px;
}

.login-block input#password {
    background: #fff url('http://i.imgur.com/Qf83FTt.png') 20px top no-repeat;
    background-size: 16px 80px;
}

.login-block input#password:focus {
    background: #fff url('http://i.imgur.com/Qf83FTt.png') 20px bottom no-repeat;
    background-size: 16px 80px;
}

.login-block input:active, .login-block input:focus {
    border: 1px solid #ff656c;
}

.login-block button {
    width: 100%;
    height: 40px;
    background: #ff656c;
    box-sizing: border-box;
    border-radius: 5px;
    border: 1px solid #e15960;
    color: #fff;
    font-weight: bold;
    text-transform: uppercase;
    font-size: 14px;
    font-family: Montserrat;
    outline: none;
    cursor: pointer;
}

.login-block button:hover {
    background: #ff7b81;
}
.box {
	width:320px;
	text-align:Center;
	margin:25px auto;
	
}
</style>

<div class="logo">autoresurs.de</div>
<?php if (isset($msg) && $msg){?>
<div class="box ">Необходимо авторизоваться</div>
<?php }?>
<div class="login-block">
	<form method="POST">
		<h1>Вход в систему</h1>
		<input type="text" value="" name="login" placeholder="<?=$translates['login']?>" id="username" />
		<input type="password" name="password" value="" placeholder="<?=$translates['pass']?>" id="password" />
		<button type="submit">Войти</button>
	</form>
</div>

