<!-- .requere -->
<div class="main">
	<h1 class="uppercase"><?=$translates['articles']?></h1>
	<div class="breadcrumbs bottom-20"><?=$bread?></div>
	
	<?php if (isset($news) && count($news)>0){?>
	<div class="post_listing">
	
		<?php foreach ($news as $dd){?>
		<div class="post_item">
			<?php if (!empty($dd['img'])){?>
			<div class="post_images">
				<a href="<?=HTTP_ROOT?>/articles/view/<?=$dd['code']?>/"><img src="<?=HTTP_ROOT?>/media/files/load/normal-<?=$dd['img']?>" title="<?=$dd['name']?>" alt="<?=$dd['name']?>"/></a>
			</div>
			<?php }?>
			
			<div class="post_content">		
				<div class="post_name"><h2><a href="<?=HTTP_ROOT?>/articles/view/<?=$dd['code']?>/"><?=$dd['name']?></a></h2></div>
				<div class="post_desc"><?=$dd['brief']?></div>
				<div class="post_info">
					<a href="<?=HTTP_ROOT?>/articles/view/<?=$dd['code']?>/"><?=$translates['front.more']?></a>
				</div>
				<div class="clear"></div>
			</div>
			<div class="clear"></div>
		</div>
		
		<?php }?>
		<div class="clear"></div>
	</div>	
	<?php }?>
	
	<div class="paging"><div class="paging-fixed"><?=PagingViewHelper::paging('/articles/page/:page:/',$pages_num,$page)?></div></div>
</div>