<?/*
<div id="tabs" class="tabs">
	<ul>
		<li><a href="#tab-1"><span><?=$translates['admin.main.priceparsers']?></span></a></li>
		<li><a href="#tab-2"><span><?=$translates['admin.main.priceparsers']?> (готовые обработчики поставщиков)</span></a></li>
	</ul>
	<div id="tab-1"><?$this->block('harvesterclaas/parse1');?></div>
	<div id="tab-2"><?$this->block('harvesterclaas/parse2');?></div>
</div>
*/?>

<h1 class="h1-header"><span>Обработка прайсов</span></h1>
<?php $this->block('harvesterclaas/parse1');?>