<?php $this->block('elements/banners');?>
<?php $this->block("elements/product");?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?=$_seo['title']?></title>
<meta name="description" content="<?=$_seo['descr']?>" />
<meta name="keywords" content="<?=$_seo['kwords']?>" />
<meta name="robots" content="index,follow" />


<meta http-equiv="cache-control" content="max-age=0" />
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="expires" content="0" />
<meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
<meta http-equiv="pragma" content="no-cache" />


<?php if ($favicon){?><link rel="shortcut icon" href="<?=HTTP_ROOT?>/media/files/settings/<?=$favicon?>?version=<?=VERSION?>"/><?php }?>

<?php 
$content_head = '';
$content_head .= "document.write('<link rel=\"stylesheet\" href=\"".HTTP_ROOT."/media-templates/css/main.css?version=".VERSION."\" type=\"text/css\" media=\"screen\" />');";
$content_head .= "document.write('<link rel=\"stylesheet\" href=\"".HTTP_ROOT."/media-templates/css/font.css?version=".VERSION."\" type=\"text/css\" media=\"screen\" />');";
$content_head .= "document.write('<link rel=\"stylesheet\" href=\"".HTTP_ROOT."/media-templates/js/dtree/dtree.css?version=".VERSION."\" type=\"text/css\" media=\"screen\" />');";
$content_head .= "document.write('<link rel=\"stylesheet\" href=\"".HTTP_ROOT."/media-templates/js/fancybox/jquery.fancybox-1.3.4.css?version=".VERSION."\" type=\"text/css\" media=\"screen\" />');";
$content_head .= "document.write('<link rel=\"stylesheet\" href=\"".HTTP_ROOT."/media-templates/css/jquery.tablesorter.css?version=".VERSION."\" type=\"text/css\" media=\"screen\" />');";
$content_head .= "document.write('<link rel=\"stylesheet\" href=\"".HTTP_ROOT."/media-templates/ui/css/ui-lightness/jquery-ui-1.10.3.custom.css?version=".VERSION."\" type=\"text/css\" media=\"screen\" />');";
$content_head .= "document.write('<link rel=\"stylesheet\" href=\"".HTTP_ROOT."/media-templates/ui/css/ui-scrollbar/jquery.mCustomScrollbar.css?version=".VERSION."\" type=\"text/css\" media=\"screen\" />');";
$content_head .= "document.write('<link rel=\"stylesheet\" href=\"".HTTP_ROOT."/media-templates/css/animate.css?version=".VERSION."\" type=\"text/css\" media=\"screen\" />');";
$content_head .= "document.write('<link rel=\"stylesheet\" href=\"".HTTP_ROOT."/media-templates/ui/jquery.jcarousel/skins/tango/skin.css?version=".VERSION."\" type=\"text/css\" media=\"screen\" />');";
$content_head .= "document.write('<link rel=\"stylesheet\" href=\"".HTTP_ROOT."/media-templates/ui/jquery.chosen/chosen.css?version=".VERSION."\" type=\"text/css\" media=\"screen\" />');";
$content_head .= "document.write('<link rel=\"stylesheet\" href=\"".HTTP_ROOT."/media-templates/css/wheels_tires.css?version=".VERSION."\" type=\"text/css\" media=\"screen\" />');";
$content_head .= "document.write('<link rel=\"stylesheet\" href=\"".HTTP_ROOT."/media-templates/js/jquery-autocomplete/jquery.autocomplete.css?version=".VERSION."\" type=\"text/css\" media=\"screen\" />');";
$content_head .= "document.write('<link rel=\"stylesheet\" href=\"".HTTP_ROOT."/media-templates/js/jquery-autocomplete/lib/thickbox.css?version=".VERSION."\" type=\"text/css\" media=\"screen\" />');";
$content_head .= "document.write('<link rel=\"stylesheet\" href=\"".HTTP_ROOT."/media-templates/ui/nivo-slider/nivo-slider.css?version=".VERSION."\" type=\"text/css\" media=\"screen\" />');";
$content_head .= "document.write('<script type=\"text/javascript\" src=\"".HTTP_ROOT."/media-templates/js/jquery.min.v1.8.3.js?version=".VERSION."\"></script>');";
$content_head .= "document.write('<script type=\"text/javascript\" src=\"".HTTP_ROOT."/media-templates/ui/js/jquery-ui-1.10.3.custom.min.js?version=".VERSION."\"></script>');";
$content_head .= "document.write('<script type=\"text/javascript\" src=\"".HTTP_ROOT."/media-templates/ui/js/jquery.mCustomScrollbar.concat.min.js?version=".VERSION."\"></script>');";
$content_head .= "document.write('<script type=\"text/javascript\" src=\"".HTTP_ROOT."/media-templates/js/dtree/dtree.js?version=".VERSION."\"></script>');";
$content_head .= "document.write('<script type=\"text/javascript\" src=\"".HTTP_ROOT."/media-templates/js/jquery.easing.1.3.js?version=".VERSION."\"></script>');";
$content_head .= "document.write('<script type=\"text/javascript\" src=\"".HTTP_ROOT."/media-templates/js/up.js?version=".VERSION."\"></script>');";
$content_head .= "document.write('<script type=\"text/javascript\" src=\"".HTTP_ROOT."/media-templates/js/table-filter.js?version=".VERSION."\"></script>');";
$content_head .= "document.write('<script type=\"text/javascript\" src=\"".HTTP_ROOT."/media-templates/js/fancybox/jquery.mousewheel-3.0.4.pack.js?version=".VERSION."\"></script>');";
$content_head .= "document.write('<script type=\"text/javascript\" src=\"".HTTP_ROOT."/media-templates/js/fancybox/jquery.fancybox-1.3.4.pack.js?version=".VERSION."\"></script>');";
$content_head .= "document.write('<script type=\"text/javascript\" src=\"".HTTP_ROOT."/media-templates/js/jquery.tablesorter.js?version=".VERSION."\"></script>');";
$content_head .= "document.write('<script type=\"text/javascript\" src=\"".HTTP_ROOT."/media-templates/js/jquery.number.min.js?version=".VERSION."\"></script>');";
$content_head .= "document.write('<script type=\"text/javascript\" src=\"".HTTP_ROOT."/media-templates/js/jq.scrollTo-min.js?version=".VERSION."\"></script>');";
$content_head .= "document.write('<script type=\"text/javascript\" src=\"".HTTP_ROOT."/media-templates/ui/jquery.jcarousel/lib/jquery.jcarousel.min.js?version=".VERSION."\"></script>');";
$content_head .= "document.write('<script type=\"text/javascript\" src=\"".HTTP_ROOT."/media-templates/ui/jquery.chosen/chosen.jquery.js?version=".VERSION."\"></script>');";
$content_head .= "document.write('<script type=\"text/javascript\" src=\"".HTTP_ROOT."/media-templates/js/wheels_tires.js?version=".VERSION."\"></script>');";
$content_head .= "document.write('<script type=\"text/javascript\" src=\"".HTTP_ROOT."/media-templates/js/batteries.js?version=".VERSION."\"></script>');";
$content_head .= "document.write('<script type=\"text/javascript\" src=\"".HTTP_ROOT."/media-templates/js/jquery-autocomplete/lib/jquery.bgiframe.min.js?version=".VERSION."\"></script>');";
$content_head .= "document.write('<script type=\"text/javascript\" src=\"".HTTP_ROOT."/media-templates/js/jquery-autocomplete/lib/jquery.ajaxQueue.js?version=".VERSION."\"></script>');";
$content_head .= "document.write('<script type=\"text/javascript\" src=\"".HTTP_ROOT."/media-templates/js/jquery-autocomplete/lib/thickbox-compressed.js?version=".VERSION."\"></script>');";
$content_head .= "document.write('<script type=\"text/javascript\" src=\"".HTTP_ROOT."/media-templates/js/jquery-autocomplete/jquery.autocomplete.js?version=".VERSION."\"></script>');";
$content_head .= "document.write('<script type=\"text/javascript\" src=\"".HTTP_ROOT."/media-templates/js/init.js?version=".VERSION."\"></script>');";
$content_head .= "document.write('<script type=\"text/javascript\" src=\"".HTTP_ROOT."/media-templates/js/jquery.tabify.js?version=".VERSION."\"></script>');";
$content_head .= "document.write('<script type=\"text/javascript\" src=\"".HTTP_ROOT."/media-templates/js/jquery.lazyload.min.js?version=".VERSION."\"></script>');";
$content_head .= "document.write('<script type=\"text/javascript\" src=\"".HTTP_ROOT."/media-templates/js/jquery.inputmask.js?version=".VERSION."\"></script>');";
$content_head .= "document.write('<script type=\"text/javascript\" src=\"".HTTP_ROOT."/media-templates/js/jquery.cookie.js?version=".VERSION."\"></script>');";
$content_head .= "document.write('<script type=\"text/javascript\" src=\"".HTTP_ROOT."/media-templates/ui/nivo-slider/jquery.nivo.slider.pack.js?version=".VERSION."\"></script>');";

$cmdd5 = md5($content_head);
$connect_head = "cache/head/".VERSION."-".$cmdd5.".js";
$connect_headp = FULL_PATH.VERSION."-".$cmdd5.".js";
if (!file_exists($connect_head)){
	file_put_contents($connect_headp, $content_head);
}
echo('<script src="'.HTTP_ROOT.'/'.$connect_head.'?version='.VERSION.'" type="text/javascript"></script>'."\n");
?>
<?php $this->block("elements/header-css");?>

<script type="text/javascript">
$(document).ready(function(){
	<?php if ($_controller != 'search'){?>
	$(".details-list").tablesorter();
	<?php }?>
	<?php if ($_controller == 'search'){?>
	function sticky() {
		var y = $(window).scrollTop();
		if (y > 165) {
			$('#search-article').css({'position': 'fixed','top': '0','left': '10','z-index':'10','border-left':'solid 1px #d8d8d8','box-shadow':'0 3px 8px #C1C1C1','width': $('#search-article').width()+'px'});
		} else {
			$('#search-article').removeAttr('style').css('width', $('#search-article').width()+'px');
		}
	};
	$(window).scroll(sticky);
	$(window).resize(sticky);
	<?php }?>
	
});
</script>
<?=$analytics?> 
<?=$header?>

<link rel="stylesheet" href="<?=HTTP_ROOT?>/media-templates/css/style.css?v=<?php echo time(); ?>" type="text/css" media="screen" />
<link rel="stylesheet" href="<?=HTTP_ROOT?>/css/cars.css" type="text/css" media="screen" />

