<div class="container">
    <div class="row">
        <main class="col-md-12 col-sm-12">
            <h1><?=$translates['yourordernumber']?> - <?=$orderData['number']?></h1>
            <div class="theme_box clearfix">
				<section class="section_offset">
               <div class="col-sm-12">
               <div class="col-sm-4">
					<h3><?=$translates['front.order.name']?></h3>
					<div class="table_wrap">
						<table>
							<tbody>
								<tr>
									<th><?=$translates['fio']?></th>
									<td colspan="2"><?=$orderData['f1']?></td>
								</tr>
								<tr>
									<th><?=$translates['front.request.vin.info14']?></th>
									<td colspan="2"><?=$orderData['f2']?></td>
								</tr>
								<tr>
									<th>E-mail</th>
									<td colspan="2"><?=$orderData['f3']?></td>
								</tr>

						</table>
					</div>
				</div>
				<div class="col-sm-4">
					<h3><?=$translates['front.delivery.block']?></h3>
					<div class="table_wrap">
						<table>
							<tbody>
								<tr>
									<th><?=$translates['f.adres_dostavki']?></th>
									<td><?=$orderData['delivery_addess']?></td>
								</tr>
								<tr>
									<th><?=$translates['front.delivery.block']?></th>
									<td><?=$orderData['delivery']?></td>
								</tr>
								<tr>
									<th><?=$translates['front.cost']?></th>
									<td><?=PriceHelper::number(PriceHelper::rate($orderData['delivery_price']))?> EUR</td>
								</tr>

						</table>
					</div>
				</div>
				<div class="col-sm-4">
					<h3><?=$translates['front.name.payment']?></h3>
					<div class="table_wrap">
						<table>
							<tbody>
								<tr>
									<td><?=$orderData['payment_name']?></td>
								</tr>
									<?php if ($merchant_data['price']>0){ ?>
										<tr>
									<th><?=$translates['front.cost']?></th>
									<td><?=PriceHelper::number(PriceHelper::rate($merchant_data['price']))?> EUR</td>
								</tr>
									<? }?>
								<?php if ($orderData['is_paid']){?>
								<tr>
									<td><b style="color:green;"><?=$translates["f.zakaz_oplachen_spasibo3"];?></b></td>
								</tr>
								<?php } ?>
						</table>
					</div>
				</div>
				</div>
				<br/>
				</section>

				<section class="section_offset">
					<h3 class="align_center"></h3>
					<h3 class="align_center"><?=$translates['list']?></h3>
				</section>
				<section class="section_offset">
				<table class="table_type_1 shopping_cart_table review">
					<thead>
											<tr>
												<th class="product_image_col align_center"><?=ucfirst($translates['front.org.img'])?></th>
												<th class="product_title_col align_center"><?=$translates['f.nazvanie_produkta']?></th>
												<th class="align_center">Art. Nr.</th>
												<th class="align_center"><?=$translates['front.price']?></th>
												<th class="product_qty_col align_center"><?=$translates['front.box']?></th>
												<th class="align_center"><?=$translates['front.cost']?></th>
											</tr>

										</thead>

										<tbody>
											<?php $sum=$sum_blr=$i=0;?>
											<?php foreach ($data as $element){?>
											<?php $i++; ?>
											
											<?php //print_r($element);?>
											<tr>
												<td data-title="<?=ucfirst($translates['front.org.img'])?>" class="product_image_col align_center">
												<?php
													if (isset($element['img'])) {
														echo "<img src='".IMGPATH.$element['img']."' width='70%'/>";
													} else {
														echo "<img src='".IMGPATH."images/no-picture.png' width='70%'/>";
													}
												?>
												</td>
												<td data-title="<?=$translates['f.nazvanie_produkta']?>" class="align_center"><?=(isset($element["supplier_name"])?$element["supplier_name"]:'')." ".(isset($element["name_".$cur_lang])?$element["name_".$cur_lang]:'');?></td>
												<td data-title="Art. Nr." class="align_center"><?=$element["art_nr"]?></td>
												<td data-title="<?=$translates['front.price']?>" class="subtotal align_center">&euro;<?=PriceHelper::number($element['old_price'])?></td>
												<td data-title="<?=$translates['front.box']?>" class="align_center"><?=$element['cc']?></td>
												<td data-title="<?=$translates['front.cost']?>" class="total align_center">&euro;<span id="new_pp_<?=$element['id']?>"><?=PriceHelper::number($element['cc']*$element['old_price'])?></span></td>
											</tr>
											<?php

												$sum += ($element['cc']*$element['old_price']);
												// $delivery_price = "5.00";
												// $total_price = $sum + $delivery_price;
											}?>
										</tbody>
										<tfoot>
											<tr>
												<td class="bold" colspan="5"><?=$translates['front.price']?></td>
												<td class="total test3"><?=PriceHelper::number($sum)?>&euro;</td>
											</tr>
											<?php if ($merchant_data['price']){ ?>
											<tr>
									<td colspan="5"><?=$translates['front.paymentplus']?></td>
									<td class="total test2"><?=PriceHelper::number(PriceHelper::rate($merchant_data['price']))?>&euro;</td>
								</tr>
											<?
											 $sum = $sum + PriceHelper::rate($merchant_data['price']);
											}?>
											<?php if ($orderData['delivery_price']&&($sum<=$delivery_data['free_from'])){
												?>
											<?php $sum = $sum + PriceHelper::rate($orderData['delivery_price']);?>
											<tr>
												<td class="bold" colspan="5"><?=$translates['front.delivery.block']?></td>
												<td class="total test1"><?=PriceHelper::number($orderData['delivery_price'])?>&euro;</td>
											</tr>
											
											<?php if ($_SESSION['pfand']>0) {
												echo '
												<tr>
													<td class="bold" colspan="5">Pfand</td>
													<td class="total test2"><span id="pfand_md5">
														'.$_SESSION["pfand"].'
													</span>&euro;</td>
												</tr>';
											}
											$sum += $_SESSION['pfand'];
											?>
											
											<?php }?>
											<tr>
												<td class="grandtotal" colspan="5"><?=$translates['front.total']?></td>
												<td class="grandtotal"><?=PriceHelper::number($sum)?>&euro;</td>
											</tr>
										</tfoot>
									</table>
				</section>
				<section class="section_offset">
				<?php
				if (!empty($merchant_data['content'])) {
					echo "<p>".$merchant_data['content']."</p>";
				}
				?>
				</section>
				<section class="section_offset">
					<?php /*if (!$orderData['is_paid']){?>
						<?php if (isset($merchants_list) && count($merchants_list)>0){?>
							<h3 class="align_center"><?=$translates['paymentlist']?></h3>
							<?php $i=0; foreach ($merchants_list as $dd){ $i++;?>
								<div class="col-md-3 col-sm-6 payments">
									<section class="infoblock type_2">

										<img alt="" src="<?=HTTP_ROOT?>/static/images/data/payments/<?=$dd['img']?>" class="aligncenter">
										<h4 class="caption"><b><?=$dd['name']?></b></h4>
										<!--<p><?=$dd['content']?></p>-->

											<a class="button_dark_grey middle_btn" href="<?=HTTP_ROOT?>/cart/paybridge/?p=<?=$dd['mcode']?>&bill=<?=$orderData['scSID']?>"><?=$translates['front.name.payment']?></a>

									</section>
								</div>
							<?php }?>
						<?php }?>
					<?php } */?>
				</section>
            </div>
        </main>
    </div>
</div>

<?php
$email =  $_SESSION['account']['email'];
$db = new mysqli('178.63.86.9', 'admin_autoresurs', 'nI82GlX4mV', 'admin_autoresursde');
$db->query(" UPDATE w_accounts SET CartScSID='' WHERE email='$email' ");
?>