<style>
.page_wrapper {background: url('<?=HTTP_ROOT?>/static/images/background-primary2.jpg') center no-repeat; background-size: cover;}
</style>
<div class="container">
    <div class="row">
        <main class="col-md-12 col-sm-12">
            <h1><?=$translates['front.about']?></h1>
            <div class="theme_box clearfix">
                <?=$page?>
            </div>
        </main>
    </div>
</div>