
<div class="container">
    <div class="row">
        <main class="col-md-12 col-sm-12">
            <h1><?=$translates['front.e404.title1']?></h1>
            <div class="theme_box clearfix align_center">
				<p><?=$translates['front.e404.title2']?></p>
				<p><?=$translates['front.e404.title3']?></p>
				<p><?=$translates['front.e404.title4']?></p>
            </div>
        </main>
    </div>
</div>

