<!--<h1>Set Languages</h1>-->

<p><a href="/staffcp/langs/view/?side=front&lang=de"><b><?=$translates['admin.langs.frontend']?></b> German</a></p>
<p><a href="/staffcp/langs/view/?side=front&lang=en"><b><?=$translates['admin.langs.frontend']?></b> English</a></p>
<p><a href="/staffcp/langs/view/?side=front&lang=fr"><b><?=$translates['admin.langs.frontend']?></b> France</a></p>
<p><a href="/staffcp/langs/view/?side=front&lang=it"><b><?=$translates['admin.langs.frontend']?></b> Italian</a></p>
<p><a href="/staffcp/langs/view/?side=front&lang=gr"><b><?=$translates['admin.langs.frontend']?></b> Greek</a></p>
<p><a href="/staffcp/langs/view/?side=front&lang=no"><b><?=$translates['admin.langs.frontend']?></b> Norwegian</a></p>
<p><a href="/staffcp/langs/view/?side=front&lang=da"><b><?=$translates['admin.langs.frontend']?></b> Danish</a></p>
<p><a href="/staffcp/langs/view/?side=front&lang=es"><b><?=$translates['admin.langs.frontend']?></b> Spanish</a></p>
<!--<hr />
<p><a href="/staffcp/langs/view/?side=back&lang=de"><b><?=$translates['admin.langs.backend']?></b> German</a></p>
<p><a href="/staffcp/langs/view/?side=back&lang=fr"><b><?=$translates['admin.langs.backend']?></b> France</a></p>
<p><a href="/staffcp/langs/view/?side=back&lang=it"><b><?=$translates['admin.langs.backend']?></b> Italian</a></p>
<p><a href="/staffcp/langs/view/?side=back&lang=gr"><b><?=$translates['admin.langs.backend']?></b> Greek</a></p>
<p><a href="/staffcp/langs/view/?side=back&lang=no"><b><?=$translates['admin.langs.backend']?></b> Norwegian</a></p>
<p><a href="/staffcp/langs/view/?side=back&lang=da"><b><?=$translates['admin.langs.backend']?></b> Danish</a></p>
<p><a href="/staffcp/langs/view/?side=back&lang=es"><b><?=$translates['admin.langs.backend']?></b> Spanish</a></p>-->