<h1 style="font-size:20px;">Спасибо, заказ оформлен.</h1>

<input type="button" name="" value="Вывести на печать заказ №<?=$bill_id?>" onclick="location='/staffcp/index/printbill/?id=<?=$bill_id?>';" class="btn btn-blue">

<input type="button" name="" value="Показать заказ №<?=$bill_id?>" onclick="location='/staffcp/index/crm/?search[number]=<?=$bill_id?>';" class="btn btn-blue">

<input type="button" name="" value="Список всех заказов" onclick="location='/staffcp/index/crm/';" class="btn btn-blue">