<h1 class="h1-header">
<span><?=$title;?></span>
<a href="<?=$listUrl;?>" class="btn btn-blue"><?=$listTitle;?></a>
</h1>
<form action="/staffcp/<?=$this->dataModel->getModelName();?>/save/" method="POST" enctype="multipart/form-data">
<div id="tabs" class="tabs">
    <ul>
    	<?php foreach ($tabs as $tabId=>$tabName){?>
        <li><a href="#tab-<?=$tabId;?>"><span><?=$tabName;?></span></a></li>
        <?php }?>
    </ul>
    <?php foreach ($tabs as $tabId=>$tabName){?>
    <div id="tab-<?=$tabId;?>">
	<table class="form">
	<?php foreach ($tabFields[$tabName] as $fieldName=>$field){?>
		<?php if ($field->hasLayout){?>
		
		<?php if ($field->fieldName == 'message' && (isset($view_details) && count($view_details)>0)){?>
		<tr>
			<td class="label">Список деталий для поиска</td>
			<td>
			
				<table class="form" id="frm">
				<tr style="background:#f1f1f1;">
					<th style="padding:5px;"><b>Артикул</b></th>
					<th style="padding:5px;"><b>Бренд</b></th>
					<th style="padding:5px;"><b>Наименование</b></th>
					<th style="padding:5px;"><b>Количество</b></th>
					<th style="padding:5px;"><b>Комментрий</b></th>
					<th style="padding:5px;"><b>Удалить</b></th>
				</tr>
				<?php foreach ($view_details as $vdet){?>
				<tr>
					<td style="padding:5px;"><input type="text" name="detailssaved[<?=$vdet['id']?>][article]" value="<?=$vdet['article']?>"/></td>
					<td style="padding:5px;"><input type="text" name="detailssaved[<?=$vdet['id']?>][brand]" value="<?=$vdet['brand']?>"/></td>
					<td style="padding:5px;"><input type="text" name="detailssaved[<?=$vdet['id']?>][name]" value="<?=$vdet['name']?>"/></td>
					<td style="padding:5px;"><input type="text" name="detailssaved[<?=$vdet['id']?>][box]" value="<?=$vdet['box']?>"/></td>
					<td style="padding:5px;"><input type="text" name="detailssaved[<?=$vdet['id']?>][comment]" value="<?=$vdet['comment']?>"/></td>
					<td style="padding:5px;"><input type="checkbox" name="detailssaved[<?=$vdet['id']?>][delete]" value="<?=$vdet['id']?>"/></td>
				</tr>
				<?php }?>
				</table>
				<a href="#" onclick="add_item_form();return false;" class="btn btn-blue">Добавить еще</a>
				<script type="text/javascript">
				function add_item_form(){
					var str = '<tr>';
					str += '<td style="padding:5px;"><input type="text" name="new_detailssaved[article][]" value=""/></td>';
					str += '<td style="padding:5px;"><input type="text" name="new_detailssaved[brand][]" value=""/></td>';
					str += '<td style="padding:5px;"><input type="text" name="new_detailssaved[name][]" value=""/></td>';
					str += '<td style="padding:5px;"><input type="text" name="new_detailssaved[box][]" value=""/></td>';
					str += '<td style="padding:5px;"><input type="text" name="new_detailssaved[comment][]" value=""/></td>';
					str += '</tr>';
					$('#frm').append(str);
				}
				</script>

			</td>
		</tr>
		<?php }?>
		
		<tr>
			<td class="label"><?=$this->dataModel->getFieldLabel($fieldName);?></td>
			<td><?=$field->getFormValue();?></td>
		</tr>
		<?php }?>
	<?php }?>
	</table>
	</div>
    <?php }?>
</div>
<input type="hidden" name="form[<?=$indexField;?>]" value="<?=$indexValue;?>" />
<input type="submit" value="<?=$submit?>" id="submit_action" class="btn btn-blue">
</form>