<h1 class="h1-header"><span><?=$translates['admin.settings.name']?></span></h1>
<div id="tabs" class="tabs">
	<ul>
		<? $i = 0;?>
		<?foreach ($groups as $groupName=>$groupSettings){?>
			<li><a href="#tab-<?=$i;?>"><?=$groupName;?></a></li>
			<? $i++;?>
		<?}?>
	</ul>
	<? $i = 0;?>
	<?foreach ($groups as $groupName=>$groupSettings){?>
		<div id="tab-<?=$i;?>">
		<table width="100%" cellspacing="0" cellpadding="0" class="list">
			<thead>
			<tr>
				<th width="40%"><?=$translates['admin.main.name']?></th>
				<th width="40%"><?=$translates['admin.main.value']?></th>
				<th width="20%"><img title="<?=$translates['admin.main.edit']?>" border="0" src="/staffcp/media/images/pencil_16.png" border="0"/></th>
			</tr>
			</thead>
			<tbody>
			<?foreach ($groupSettings as $settings){?>
			<tr>
				<td><?=$settings['name'];?></td>
				<td>
				<?if ($settings['type'] == 'text'){?>
				<i>... text ...</i>
				<?}elseif ($settings['type'] == 'htmlarea'){?>
				<i>... html-code ...</i>
				<?}elseif ($settings['type'] == 'password'){?>
				<i>... password ...</i>
				<?}elseif ($settings['type'] == 'checkbox'){?>
				<?='<img src="/staffcp/media/images/checkbox'.$settings['value'].'.gif" >';?>
				<?}else{?>
				<?=$settings['value'];?>
				<?}?>
				</td>
				<td><a href="/staffcp/settings/edit/?id=<?=$settings['id'];?>"><img title="<?=$translates['admin.main.edit']?>" border="0" src="/staffcp/media/images/pencil_16.png" border="0"/></a></td>
			</tr>
			<?}?>
			</tbody>
		</table>
		<br/><br/>
		</div>
		<? $i++;?>
	<?}?>
</div>

